# Document Structure Diagnostic Notebook

This notebook is built around the project's actual architecture.

**Goal:** understand how a heterogeneous PDF is structured so that expensive downstream extraction (LLM / NER / targeted OCR) can be applied only to useful pages or sections.

```text
PDF
├── bookmarks / outline
└── PyMuPDF page analysis
    ├── raw text
    ├── text blocks / typography
    ├── tables
    └── scan/image evidence
             ↓
       TOC detection
             ↓
       title candidates
             ↓
       TOC ↔ title matching
             ↓
       boundary detection
             ↓
       hierarchy + page ranges
             ↓
          validation
             ↓
       useful-page routing
             ↓
        LLM / NER / OCR
```

The notebook is **diagnostic-first**: we inspect the evidence behind decisions, not just the final score.

## 1. Configuration

Set the PDF you want to investigate. The notebook uses **PyMuPDF** and the project's `src.document_structure` modules.

In [1]:
from pathlib import Path
import sys
import inspect
import pandas as pd
import pymupdf as fitz

PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / "src").exists() and (PROJECT_ROOT.parent / "src").exists():
    PROJECT_ROOT = PROJECT_ROOT.parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

PDF_PATH = PROJECT_ROOT / "data" / "raw" / "MYCOM Operating and Maintenance Manual Refrigeration Unit (1).pdf"

print("PROJECT_ROOT:", PROJECT_ROOT)
print("PDF_PATH:", PDF_PATH)

PROJECT_ROOT: c:\Users\intel\Downloads\industrial-equipment-data-extraction
PDF_PATH: c:\Users\intel\Downloads\industrial-equipment-data-extraction\data\raw\MYCOM Operating and Maintenance Manual Refrigeration Unit (1).pdf

## 2. Open PDF and inspect native metadata

In [2]:
doc = fitz.open(PDF_PATH)

print("PDF pages:", len(doc))
print("\nMetadata:")
for key, value in doc.metadata.items():
    print(f"  {key}: {value}")

PDF pages: 1068

Metadata:
  format: PDF 1.5
  title: untitled
  author: mara.riga
  subject:
  keywords:
  creator: Adobe Acrobat 10.1.6
  producer: macOS Version 14.4.1 (assemblage 23E224) Quartz PDFContext, AppendMode 1.1
  creationDate: D:20140616145557Z00'00'
  modDate: D:20260701105902Z00'00'
  trapped:
  encryption: None

## 3. Inspect PDF bookmarks / outline

Bookmarks are an independent structural signal. They are useful when present, but they are not automatically ground truth.

In [3]:
outline = doc.get_toc(simple=False)

print("Bookmark entries:", len(outline))
for item in outline[:100]:
    level, title, page = item[:3]
    print(f"L{level:<2} PDF page {page:<4} {title}")

Bookmark entries: 0

## 4. Run the actual `PageAnalyzer`

The page layer must preserve **raw text AND tables**. This is essential for table-based TOCs whose section/title/page relationships can be destroyed by flattening cells into one text stream.

In [4]:
from src.document_structure.page_analysis import PageAnalyzer

page_analyzer = PageAnalyzer()
pages_meta = page_analyzer.extract_document(doc)

print("Pages analyzed:", len(pages_meta))
print("Page object:", type(pages_meta[0]).__name__ if pages_meta else None)

warning: The `fitz` API is deprecated and will be removed in future. Use `import pymupdf` instead.
Consider using the pymupdf_layout package for a greatly improved page layout analysis.
Pages analyzed: 1068
Page object: PageRepresentation

## 5. Inspect the page representation

In [5]:
def get_attr(obj, *names, default=None):
    for name in names:
        if hasattr(obj, name):
            return getattr(obj, name)
    return default

if pages_meta:
    page = pages_meta[0]
    print(type(page).__name__)
    if hasattr(page, "__dict__"):
        for key, value in vars(page).items():
            print(f"{key}: {type(value).__name__}")

PageRepresentation
page_number: int
raw_text: str
text_blocks: list
tables: list
image_count: int
is_scanned: bool
width: float
height: float

## 6. Build extraction inventory

This separates an **extraction problem** from a **TOC detection problem**.

In [6]:
rows = []
for pdf_page, page in enumerate(pages_meta, start=1):
    text = get_attr(page, "raw_text", "text", default="") or ""
    blocks = get_attr(page, "text_blocks", "blocks", default=[]) or []
    tables = get_attr(page, "tables", "extracted_tables", default=[]) or []
    rows.append({
        "pdf_page": pdf_page,
        "text_chars": len(text),
        "text_blocks": len(blocks),
        "table_count": len(tables),
        "has_text": bool(text.strip()),
        "has_table": bool(tables),
    })

page_inventory = pd.DataFrame(rows)
display(page_inventory.head(25))
print("Pages with tables:", int(page_inventory["has_table"].sum()))
print("Pages with no extracted text:", int((~page_inventory["has_text"]).sum()))

    pdf_page  text_chars  text_blocks  table_count  has_text  has_table
0          1         490           14            1      True       True
1          2         364           14            2      True       True
2          3         338           10            1      True       True
3          4         309            8            1      True       True
4          5        2609          101            1      True       True
5          6        1251           45            1      True       True
6          7         310            8            1      True       True
7          8           0            0            0     False      False
8          9         367           11            1      True       True
9         10         321            9            1      True       True
10        11        2626           99            1      True       True
11        12           0            0            0     False      False
12        13         365           13            1      True       True
13        14         326            5            1      True       True
14        15        1552           71            1      True       True
15        16         309            8            1      True       True
16        17           0            0            0     False      False
17        18           0            0            0     False      False
18        19         303            8            1      True       True
19        20           0            0            0     False      False
20        21         394           15            1      True       True
21        22         401           10            1      True       True
22        23         330           11            2      True       True
23        24        2818            6            1      True       True
24        25           0            0            0     False      False

Pages with tables: 520
Pages with no extracted text: 167

## 7. Inspect the known TOC pages

Start with the pages discussed during development: **6, 7 and 187**.

They are 1-based PDF page numbers. Inspect raw text and tables separately.

In [ ]:
FOCUS_PAGES = [6, 7, 187]

for page_number in FOCUS_PAGES:
    if not 1 <= page_number <= len(pages_meta):
        print("Skipping invalid page:", page_number)
        continue

    page = pages_meta[page_number - 1]
    text = get_attr(page, "raw_text", "text", default="") or ""
    tables = get_attr(page, "tables", "extracted_tables", default=[]) or []

    print("\n")
    print(f"PDF PAGE {page_number}")
    print("\n--- RAW TEXT ---")
    print(text[:8000])
    print(f"\n--- TABLES ({len(tables)}) ---")
    for i, table in enumerate(tables, start=1):
        print(f"\nTABLE {i}:")
        print(table)

====================================================================================================
PDF PAGE 6
====================================================================================================

--- RAW TEXT ---
PROJECT:
AMMONIASTORAGEREFRIGERATION&TRANSFERSYSTEM/AMMONIACOMPRESSOR
VENDORNAME:
MayekawaMycom
P.O.No.
2012123PO3563
AREA:
455A
FINAL DOCUMENTATION
OPERATING AND MAINTENANCE DATA: TECHNICAL DOCUMENTS
Description
Doc. No.
5.4
5.5
5.6
5.7
5.8
5.9
6.
PIPING
6.1
6.2
6.3
7.
7.1
7.2
7.3
7.4
7.5
7.6
7.7
7.8
7.9
7.10
7.11
LOCALGAUGEBOARD&JBLAYOUT
P1-REF-2012-123-018
CABLESLIST
P1-REF-LST-12-123-004
INSTRUMENTSANDCABLETRAYLAYOUT
P1-REF-2012-123-004
P1-REF-LST-12-123-006
PACKAGEI/OLIST
CONTROLSYSTEMBLOCKDIAGRAM
P1-REF-2012-123-017
INSTRUMENTATION&CONTROL
INSTRUMENTLIST&SETTING
P1-REF-LST-12-123-005
CAUSE&EFFECTSCHART
P1-REF-LST-12-123-011
PUMPMOTORSDRAWING
P1-REF-2012-123-025
P1-REF-2012-123-031
MAINMOTORTERMINALBOXES
P1-REF-2012-123-030
FANMOTORSDRAWING
P1-REF-2012-123-024
P1-REF-DSS-12-123-020
P1-REF-SPC-12-123-001
PIPINGCLASS
ELECTRICALHOOKUP
INSTRUMENTHOOKUP
P1-REF-2012-123-028
SAFETYVALVESCALCULATIONSHEETS
P1-REF-RCA-12-123-003
INSTRUMENTDATASHEETS
P1-REF-DSS-12-123-002
FANMOTORSDATASHEET&CURVES
P1-REF-DSS-12-123-019
MAINMOTORTESTINGPROCEDURE
P1-REF-PRD-12-123-006
PIPINGTESTINGPROCEDURE
P1-REF-PRD-12-123-014
PUMPMOTORSDATASHEET&CURVES
LINELIST
P1-REF-LST-12-123-008


--- TABLES (1) ---

TABLE 1:
TableRepresentation(rows=[['', 'Description', 'Doc. No.'], ['5.4', 'MAIN\x02MOTOR\x02TERMINAL\x02BOXES', 'P1-REF-2012-123-030'], ['5.5', 'MAIN\x02MOTOR\x02TESTING\x02PROCEDURE', 'P1-REF-PRD-12-123-006'], ['5.6', 'FAN\x02MOTORS\x02DRAWING', 'P1-REF-2012-123-024'], ['5.7', 'FAN\x02MOTORS\x02DATA\x02SHEET\x02&\x02CURVES', 'P1-REF-DSS-12-123-019'], ['5.8', 'PUMP\x02MOTORS\x02DRAWING', 'P1-REF-2012-123-025'], ['5.9', 'PUMP\x02MOTORS\x02DATA\x02SHEET\x02&\x02CURVES', 'P1-REF-DSS-12-123-020'], ['', '', ''], ['6.', 'PIPING', ''], ['6.1', 'LINE\x02LIST', 'P1-REF-LST-12-123-008'], ['6.2', 'PIPING\x02TESTING\x02PROCEDURE', 'P1-REF-PRD-12-123-014'], ['6.3', 'PIPING\x02CLASS', 'P1-REF-SPC-12-123-001'], ['', '', ''], ['7.', 'INSTRUMENTATION\x02&\x02CONTROL', ''], ['7.1', 'CONTROL\x02SYSTEM\x02BLOCK\x02DIAGRAM', 'P1-REF-2012-123-017'], ['7.2', 'INSTRUMENT\x02LIST\x02&\x02SETTING', 'P1-REF-LST-12-123-005'], ['7.3', 'INSTRUMENT\x02DATA\x02SHEETS', 'P1-REF-DSS-12-123-002'], ['7.4', 'INSTRUMENT\x02HOOK\x02UP', 'P1-REF-2012-123-028'], ['7.5', 'ELECTRICAL\x02HOOK\x02UP', 'P1-REF-2012-123-031'], ['7.6', 'SAFETY\x02VALVES\x02CALCULATION\x02SHEETS', 'P1-REF-RCA-12-123-003'], ['7.7', 'CAUSE\x02&\x02EFFECTS\x02CHART', 'P1-REF-LST-12-123-011'], ['7.8', 'PACKAGE\x02I/O\x02LIST', 'P1-REF-LST-12-123-006'], ['7.9', 'CABLES\x02LIST', 'P1-REF-LST-12-123-004'], ['7.10', 'LOCAL\x02GAUGE\x02BOARD\x02&\x02JB\x02LAY\x02OUT', 'P1-REF-2012-123-018'], ['7.11', 'INSTRUMENTS\x02AND\x02CABLE\x02TRAY\x02LAY\x03OUT', 'P1-REF-2012-123-004'], ['', '', '']], columns=['column_0', 'column_1', 'column_2'], bbox=(47.15196990966797, 138.03709411621094, 547.2897033691406, 458.71401596069336), extraction_method='pymupdf', confidence=None)

====================================================================================================
PDF PAGE 7
====================================================================================================

--- RAW TEXT ---
REV.
0
CLIENT:
OCP - MAROC PHOSPHORE
Vendor Job.N°:
2012-123
PROJ.N°:
Q3600XXX
Unit:
455A
PLANT:
ODI at P1 SITE
OCP Doc. Code:
455A-REF-PRD- 009
N°2 AMMONIA STORAGE TANKS
Vendor Doc.No.:
P1-REF-PRD-12-123-009
1. GENERAL DOCUMENTS
1
of
LOCATION:
JORF LASFAR - MOROCCO
Sheet
1
OCP - MAROC PHOSPHORE


--- TABLES (1) ---

TABLE 1:
TableRepresentation(rows=[['', None, 'CLIENT:\nPROJ.N°:\nPLANT:', 'OCP - MAROC PHOSPHORE\nQ3600XXX\nODI at P1 SITE\nN°2 AMMONIA STORAGE TANKS\nJORF LASFAR - MOROCCO', 'Vendor Job.N°:\nUnit:\nOCP Doc. Code:\nVendor Doc.No.:', '2012-123\n455A\n455A-REF-PRD- 009\nP1-REF-PRD-12-123-009', None], ['', None, 'LOCATION:', None, 'Sheet 1 of 1\nREV. 0', None, None], ['OCP - MAROC PHOSPHORE', None, None, None, None, None, None], ['', '1. GENERAL DOCUMENTS', None, None, None, None, ''], ['', None, None, None, None, None, None]], columns=['column_0', 'column_1', 'column_2', 'column_3', 'column_4', 'column_5', 'column_6'], bbox=(21.02169282095773, 47.75202941894531, 573.3252563476562, 793.5490519205729), extraction_method='pymupdf', confidence=None)

====================================================================================================
PDF PAGE 187
====================================================================================================

--- RAW TEXT ---
REV.
0
CLIENT:
OCP - MAROC PHOSPHORE
Vendor Job.N°:
2012-123
PROJ.N°:
Q3600XXX
Unit:
455A
PLANT:
ODI at P1 SITE
OCP Doc. Code:
455A-REF-PRD- 009
N°2 AMMONIA STORAGE TANKS
Vendor Doc.No.:
P1-REF-PRD-12-123-009
1
of
LOCATION:
JORF LASFAR - MOROCCO
Sheet
1
INSTALLATION
OPERATION
AND MAINTENANCE
OCP - MAROC PHOSPHORE


--- TABLES (1) ---

TABLE 1:
TableRepresentation(rows=[['', None, 'CLIENT:\nPROJ.N°:\nPLANT:', 'OCP - MAROC PHOSPHORE\nQ3600XXX\nODI at P1 SITE\nN°2 AMMONIA STORAGE TANKS\nJORF LASFAR - MOROCCO', 'Vendor Job.N°:\nUnit:\nOCP Doc. Code:\nVendor Doc.No.:', '2012-123\n455A\n455A-REF-PRD- 009\nP1-REF-PRD-12-123-009', None], ['', None, 'LOCATION:', None, 'Sheet 1 of 1\nREV. 0', None, None], ['OCP - MAROC PHOSPHORE', None, None, None, None, None, None], ['', 'INSTALLATION\nOPERATION\nAND MAINTENANCE', None, None, None, None, ''], ['', None, None, None, None, None, None]], columns=['column_0', 'column_1', 'column_2', 'column_3', 'column_4', 'column_5', 'column_6'], bbox=(21.02169282095773, 47.75202941894531, 573.3252563476562, 793.5490519205729), extraction_method='pymupdf', confidence=None)

## 8. Table-vs-text extraction experiment

Hypothesis:

```text
raw text only
    ↓
"1 Introduction 3 1.1 Scope 4 ..."
```

can lose column relationships, while table extraction can preserve:

```text
section | title | printed page
```

This is why tables are first-class input to TOC analysis.

In [8]:
from src.document_structure.toc import TOCDetector
detector = TOCDetector()
result = detector.explain_page(pages_meta[5])  # page 6, 0-indexed
print(result["is_toc"], result["confidence"])
print(result["positive_evidence"])

True 0.5
{'strong_toc_keywords': [], 'document_register_header': True, 'section_structure': {'match_count': 0, 'ratio': 0.0}, 'page_references': {'match_count': 0, 'ratio': 0.0}, 'dot_leaders': {'match_count': 0, 'ratio': 0.0}, 'toc_tables': [{'rows': 26, 'columns': 3, 'bbox': (47.15196990966797, 138.03709411621094, 547.2897033691406, 458.71401596069336), 'extraction_method': 'pymupdf', 'sample_rows': [['', 'Description', 'Doc. No.'], ['5.4', 'MAIN\x02MOTOR\x02TERMINAL\x02BOXES', 'P1-REF-2012-123-030'], ['5.5', 'MAIN\x02MOTOR\x02TESTING\x02PROCEDURE', 'P1-REF-PRD-12-123-006'], ['5.6', 'FAN\x02MOTORS\x02DRAWING', 'P1-REF-2012-123-024'], ['5.7', 'FAN\x02MOTORS\x02DATA\x02SHEET\x02&\x02CURVES', 'P1-REF-DSS-12-123-019']]}], 'toc_table_count': 1, 'entry_like_structure': {'line_count': 76, 'short_line_ratio': 1.0}, 'layout_consistency': {'consistent_entry_structure': False, 'page_reference_ratio': 0.0}}

## 9. Run the actual `TOCDetector`

The detector should combine multiple signals.

**Positive evidence** may include section numbering, page-reference patterns, TOC wording, dot leaders/alignment, table structure and entry density.

**Negative evidence** may include index-like structure, ordinary tables, prose dominance, or weak section/page-reference patterns.

This matters because an `Index` page is not necessarily useful for reconstructing document hierarchy, while a real TOC may have a non-obvious title such as `Final Documentation`.

In [9]:
from src.document_structure.toc import TOCDetector

toc_detector = TOCDetector(toc_score_threshold=0.40)
detected_tocs = toc_detector.detect_printed_tocs(pages_meta)

print("Detected TOC regions:", len(detected_tocs))
for i, region in enumerate(detected_tocs, 1):
    print(f"\n--- TOC REGION {i} ---")
    print("type:", region.toc_type)
    print("pages:", region.page_numbers)
    print("confidence:", round(region.confidence, 3))
    print("entries:", len(region.entries))

Detected TOC regions: 18

--- TOC REGION 1 ---
type: printed
pages: [5, 6]
confidence: 0.5
entries: 69

--- TOC REGION 2 ---
type: printed
pages: [188]
confidence: 0.5
entries: 36

--- TOC REGION 3 ---
type: printed
pages: [282, 283, 284, 285]
confidence: 0.43
entries: 20

--- TOC REGION 4 ---
type: printed
pages: [409]
confidence: 0.63
entries: 77

--- TOC REGION 5 ---
type: printed
pages: [549]
confidence: 0.5
entries: 2

--- TOC REGION 6 ---
type: printed
pages: [554]
confidence: 0.5
entries: 3

--- TOC REGION 7 ---
type: printed
pages: [599]
confidence: 0.5
entries: 2

--- TOC REGION 8 ---
type: printed
pages: [601]
confidence: 0.474
entries: 6

--- TOC REGION 9 ---
type: printed
pages: [603]
confidence: 0.5
entries: 3

--- TOC REGION 10 ---
type: printed
pages: [635, 636]
confidence: 0.5
entries: 21

--- TOC REGION 11 ---
type: printed
pages: [751]
confidence: 0.5
entries: 2

--- TOC REGION 12 ---
type: printed
pages: [753]
confidence: 0.474
entries: 6

--- TOC REGION 13 ---
type: printed
pages: [776]
confidence: 0.426
entries: 18

--- TOC REGION 14 ---
type: printed
pages: [794]
confidence: 0.541
entries: 31

--- TOC REGION 15 ---
type: printed
pages: [876]
confidence: 0.4
entries: 0

--- TOC REGION 16 ---
type: printed
pages: [938]
confidence: 0.4
entries: 0

--- TOC REGION 17 ---
type: printed
pages: [1000]
confidence: 0.4
entries: 0

--- TOC REGION 18 ---
type: printed
pages: [1068]
confidence: 0.499
entries: 10

## 10. Inspect TOC regions and their entries

In [ ]:
def dump_object(obj):
    if hasattr(obj, "model_dump"):
        data = obj.model_dump()
    elif hasattr(obj, "__dict__"):
        data = vars(obj)
    else:
        print(repr(obj))
        return
    for key, value in data.items():
        print(f"{key}: {value}")

for i, region in enumerate(detected_tocs, 1):
    print()
    print(f"TOC REGION {i}")
    dump_object(region)

    print("\nFirst entries:")
    for entry in region.entries[:30]:
        print(
            f"[{getattr(entry,'section_number',None) or '•':>10}] "
            f"L{getattr(entry,'level',None)} "
            f"{str(getattr(entry,'text',''))[:90]:<90} "
            f"printed_ref={getattr(entry,'printed_page_ref',None)}"
        )

====================================================================================================
TOC REGION 1
====================================================================================================
pages: [5, 6]
entries: [TOCEntry(text='DOCUMENTS\x02&\x02DRAWINGS\x02LIST', section_number='1.1', level=2, printed_page_ref='P1-REF-LST-12-123-007', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='SUBVENDOR\x02LIST', section_number='1.2', level=2, printed_page_ref='P1-REF-LST-12-123-003', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='NOISE\x02DATA\x02SHEET', section_number='1.3', level=2, printed_page_ref='P1-REF-DSS-12-123-008', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='LUBRICANT\x02LIST', section_number='1.4', level=2, printed_page_ref='P1-REF-SPC-12-123-002', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='PAINTING\x02SPECIFICATIONS', section_number='1.5', level=2, printed_page_ref='P1-REF-SPC-12-123-003', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='PACKAGE\x02DRAWINGS', section_number='2', level=1, printed_page_ref=None, reference_kind=None, source_page=5, confidence=0.8), TOCEntry(text='PROCESS\x02FLOW\x02DIAGRAM', section_number='2.1', level=2, printed_page_ref='P1-REF-2012-123-014', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='P&ID\x02REFRIGERATION\x02UNIT', section_number='2.2', level=2, printed_page_ref='P1-REF-2012-123-001', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='GENERAL\x02ARRANGEMENT\x02DRAWING', section_number='2.3', level=2, printed_page_ref='P1-REF-2012-123-003', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='FOUNDATION\x02LAY\x03OUT\x02', section_number='2.4', level=2, printed_page_ref='P1-REF-2012-123-012', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='P.V.\x02&\x02H.E.', section_number='3', level=1, printed_page_ref=None, reference_kind=None, source_page=5, confidence=0.8), TOCEntry(text='AIR\x02COOLER\x02CONDENSER\x02DATA\x02SHEET', section_number='3.1', level=2, printed_page_ref='P1-REF-DSS-12-123-011', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='AIR\x02COOLER\x02CONDENSER\x02GENERAL\x02ARRANGEMENT', section_number='3.2', level=2, printed_page_ref='P1-REF-2012-123-005', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='AIR\x02COOLER\x02CONDENSER\x02TUBE\x02BUNDLE\x02DRAWING', section_number='3.3', level=2, printed_page_ref='P1-REF-2012-123-016', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='AIR\x02COOLER\x02CONDENSER\x02STRUCTURAL\x02PART\x02LIST\x02&\x02ASSEMBLY', section_number='3.4', level=2, printed_page_ref='P1-REF-2012-123-034', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='AIR\x02COOLER\x02CONDENSER\x02TUBE\x02BUNDLE\x02FRAME\x02DRAWING', section_number='3.5', level=2, printed_page_ref='P1-REF-2012-123-035', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='AIR\x02CONDENSER\x02TESTING\x02PROCEDURE', section_number='3.6', level=2, printed_page_ref='P1-REF-PRD-12-123-001', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='ECONOMIZER\x02DATA\x02SHEET', section_number='3.7', level=2, printed_page_ref='P1-REF-DSS-12-123-012', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='ECONOMIZER\x02ASSEMBLY\x02DRAWING', section_number='3.8', level=2, printed_page_ref='P1-REF-2012-123-006', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='KO\x02DRUM\x02DATA\x02SHEET', section_number='3.9', level=2, printed_page_ref='P1-REF-DSS-12-123-013', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='KO\x02DRUM\x02ASSEMBLY\x02DRAWING', section_number='3.10', level=2, printed_page_ref='P1-REF-2012-123-007', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='OIL\x02COOLER\x02DATA\x02SHEET', section_number='3.11', level=2, printed_page_ref='P1-REF-DSS-12-123-014', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='OIL\x02COOLER\x02\x02ASSEMBLY\x02DRAWING', section_number='3.12', level=2, printed_page_ref='P1-REF-2012-123-008', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='RECEIVER\x02DATA\x02SHEET', section_number='3.13', level=2, printed_page_ref='P1-REF-DSS-12-123-017', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='RECEIVER\x02ASSEMBLY\x02DRAWING', section_number='3.14', level=2, printed_page_ref='P1-REF-2012-123-010', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='OIL\x02SEPARATOR\x02DATA\x02SHEET', section_number='3.15', level=2, printed_page_ref='P1-REF-DSS-12-123-016', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='OIL\x02SEPARATOR\x02ASSEMBLY\x02DRAWING', section_number='3.16', level=2, printed_page_ref='P1-REF-2012-123-009', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='SUCTION\x02FILTER\x02DATA\x02SHEET', section_number='3.17', level=2, printed_page_ref='P1-REF-DSS-12-123-018', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='SUCTION\x02FILTER\x02ASSEMBLY\x02DRAWING', section_number='3.18', level=2, printed_page_ref='P1-REF-2012-123-011', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='OIL\x02FILTER\x02DATA\x02SHEET', section_number='3.19', level=2, printed_page_ref='P1-REF-DSS-12-123-015', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='OIL\x02FILTER\x02ASSEMBLY\x02DRAWING\x02', section_number='3.20', level=2, printed_page_ref='P1-REF-2012-123-019', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='P.V.\x02&\x02H.E.\x02TESTING\x02PROCEDURES', section_number='3.21', level=2, printed_page_ref='P1-REF-PRD-12-123-013', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='COMPRESSOR\x02&\x02PUMPS', section_number='4', level=1, printed_page_ref=None, reference_kind=None, source_page=5, confidence=0.8), TOCEntry(text='COMPRESSOR\x02DRAWINGS\x02(OUTLINE\x02&\x02SECTIONAL)', section_number='4.1', level=2, printed_page_ref='P1-REF-2012-123-020', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='COMPRESSOR\x02MECHANICAL\x02SEAL\x02DRAWING', section_number='4.2', level=2, printed_page_ref='P1-REF-DSS-12-123-007', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='COMPRESSOR\x02TESTING\x02PROCEDURE', section_number='4.3', level=2, printed_page_ref='P1-REF-PRD-12-123-002', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='COMPRESSOR\x02PERFORMANCE\x02CURVE', section_number='4.4', level=2, printed_page_ref='P1-REF-DSS-12-123-023', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='COMPRESSOR\x02STARTING\x02TORQUE\x02CURVE', section_number='4.5', level=2, printed_page_ref='P1-REF-DSS-12-123-004', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='TRAIN\x02TORSIONAL\x02ANALYSIS', section_number='4.6', level=2, printed_page_ref='P1-REF-RCA-12-123-010', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='COMPRESSOR\x02DATA\x02SHEETS', section_number='4.7', level=2, printed_page_ref='P1-REF-DSS-12-123-003', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='COMPRESSOR\x02COUPLING\x02\x02DRAWING', section_number='4.8', level=2, printed_page_ref='P1-REF-2012-123-022', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='OIL\x02PUMP\x02DRAWING', section_number='4.9', level=2, printed_page_ref='P1-REF-2012-123-027', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='OIL\x02PUMP\x02DATA\x02SHEET', section_number='4.10', level=2, printed_page_ref='P1-REF-DSS-12-123-021', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='ELECTRICAL\x02', section_number='5', level=1, printed_page_ref=None, reference_kind=None, source_page=5, confidence=0.8), TOCEntry(text='ELECTRICAL\x02&\x02UTILITIES\x02CONSUMPTION\x02LIST', section_number='5.1', level=2, printed_page_ref='P1-REF-LST-12-123-003', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='MAIN\x02MOTOR\x02DRAWING', section_number='5.2', level=2, printed_page_ref='P1-REF-2012-123-027', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='MAIN\x02MOTOR\x02DATA\x02SHEETS', section_number='5.3', level=2, printed_page_ref='P1-REF-DSS-12-123-005', reference_kind='doc_code', source_page=5, confidence=0.8), TOCEntry(text='MAIN\x02MOTOR\x02TERMINAL\x02BOXES', section_number='5.4', level=2, printed_page_ref='P1-REF-2012-123-030', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='MAIN\x02MOTOR\x02TESTING\x02PROCEDURE', section_number='5.5', level=2, printed_page_ref='P1-REF-PRD-12-123-006', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='FAN\x02MOTORS\x02DRAWING', section_number='5.6', level=2, printed_page_ref='P1-REF-2012-123-024', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='FAN\x02MOTORS\x02DATA\x02SHEET\x02&\x02CURVES', section_number='5.7', level=2, printed_page_ref='P1-REF-DSS-12-123-019', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='PUMP\x02MOTORS\x02DRAWING', section_number='5.8', level=2, printed_page_ref='P1-REF-2012-123-025', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='PUMP\x02MOTORS\x02DATA\x02SHEET\x02&\x02CURVES', section_number='5.9', level=2, printed_page_ref='P1-REF-DSS-12-123-020', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='PIPING', section_number='6', level=1, printed_page_ref=None, reference_kind=None, source_page=6, confidence=0.8), TOCEntry(text='LINE\x02LIST', section_number='6.1', level=2, printed_page_ref='P1-REF-LST-12-123-008', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='PIPING\x02TESTING\x02PROCEDURE', section_number='6.2', level=2, printed_page_ref='P1-REF-PRD-12-123-014', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='PIPING\x02CLASS', section_number='6.3', level=2, printed_page_ref='P1-REF-SPC-12-123-001', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='INSTRUMENTATION\x02&\x02CONTROL', section_number='7', level=1, printed_page_ref=None, reference_kind=None, source_page=6, confidence=0.8), TOCEntry(text='CONTROL\x02SYSTEM\x02BLOCK\x02DIAGRAM', section_number='7.1', level=2, printed_page_ref='P1-REF-2012-123-017', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='INSTRUMENT\x02LIST\x02&\x02SETTING', section_number='7.2', level=2, printed_page_ref='P1-REF-LST-12-123-005', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='INSTRUMENT\x02DATA\x02SHEETS', section_number='7.3', level=2, printed_page_ref='P1-REF-DSS-12-123-002', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='INSTRUMENT\x02HOOK\x02UP', section_number='7.4', level=2, printed_page_ref='P1-REF-2012-123-028', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='ELECTRICAL\x02HOOK\x02UP', section_number='7.5', level=2, printed_page_ref='P1-REF-2012-123-031', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='SAFETY\x02VALVES\x02CALCULATION\x02SHEETS', section_number='7.6', level=2, printed_page_ref='P1-REF-RCA-12-123-003', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='CAUSE\x02&\x02EFFECTS\x02CHART', section_number='7.7', level=2, printed_page_ref='P1-REF-LST-12-123-011', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='PACKAGE\x02I/O\x02LIST', section_number='7.8', level=2, printed_page_ref='P1-REF-LST-12-123-006', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='CABLES\x02LIST', section_number='7.9', level=2, printed_page_ref='P1-REF-LST-12-123-004', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='LOCAL\x02GAUGE\x02BOARD\x02&\x02JB\x02LAY\x02OUT', section_number='7.10', level=2, printed_page_ref='P1-REF-2012-123-018', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='INSTRUMENTS\x02AND\x02CABLE\x02TRAY\x02LAY\x03OUT', section_number='7.11', level=2, printed_page_ref='P1-REF-2012-123-004', reference_kind='doc_code', source_page=6, confidence=0.8)]
confidence: 0.5
evidence: {}
toc_type: printed
has_page_references: False
scope_title: None

First entries:
[       1.1] L2 DOCUMENTS&DRAWINGSLIST                                                                  printed_ref=P1-REF-LST-12-123-007
[       1.2] L2 SUBVENDORLIST                                                                             printed_ref=P1-REF-LST-12-123-003
[       1.3] L2 NOISEDATASHEET                                                                           printed_ref=P1-REF-DSS-12-123-008
[       1.4] L2 LUBRICANTLIST                                                                             printed_ref=P1-REF-SPC-12-123-002
[       1.5] L2 PAINTINGSPECIFICATIONS                                                                    printed_ref=P1-REF-SPC-12-123-003
[         2] L1 PACKAGEDRAWINGS                                                                           printed_ref=None
[       2.1] L2 PROCESSFLOWDIAGRAM                                                                       printed_ref=P1-REF-2012-123-014
[       2.2] L2 P&IDREFRIGERATIONUNIT                                                                    printed_ref=P1-REF-2012-123-001
[       2.3] L2 GENERALARRANGEMENTDRAWING                                                                printed_ref=P1-REF-2012-123-003
[       2.4] L2 FOUNDATIONLAYOUT                                                                        printed_ref=P1-REF-2012-123-012
[         3] L1 P.V.&H.E.                                                                                printed_ref=None
[       3.1] L2 AIRCOOLERCONDENSERDATASHEET                                                            printed_ref=P1-REF-DSS-12-123-011
[       3.2] L2 AIRCOOLERCONDENSERGENERALARRANGEMENT                                                   printed_ref=P1-REF-2012-123-005
[       3.3] L2 AIRCOOLERCONDENSERTUBEBUNDLEDRAWING                                                   printed_ref=P1-REF-2012-123-016
[       3.4] L2 AIRCOOLERCONDENSERSTRUCTURALPARTLIST&ASSEMBLY                                       printed_ref=P1-REF-2012-123-034
[       3.5] L2 AIRCOOLERCONDENSERTUBEBUNDLEFRAMEDRAWING                                             printed_ref=P1-REF-2012-123-035
[       3.6] L2 AIRCONDENSERTESTINGPROCEDURE                                                            printed_ref=P1-REF-PRD-12-123-001
[       3.7] L2 ECONOMIZERDATASHEET                                                                      printed_ref=P1-REF-DSS-12-123-012
[       3.8] L2 ECONOMIZERASSEMBLYDRAWING                                                                printed_ref=P1-REF-2012-123-006
[       3.9] L2 KODRUMDATASHEET                                                                         printed_ref=P1-REF-DSS-12-123-013
[      3.10] L2 KODRUMASSEMBLYDRAWING                                                                   printed_ref=P1-REF-2012-123-007
[      3.11] L2 OILCOOLERDATASHEET                                                                      printed_ref=P1-REF-DSS-12-123-014
[      3.12] L2 OILCOOLERASSEMBLYDRAWING                                                               printed_ref=P1-REF-2012-123-008
[      3.13] L2 RECEIVERDATASHEET                                                                        printed_ref=P1-REF-DSS-12-123-017
[      3.14] L2 RECEIVERASSEMBLYDRAWING                                                                  printed_ref=P1-REF-2012-123-010
[      3.15] L2 OILSEPARATORDATASHEET                                                                   printed_ref=P1-REF-DSS-12-123-016
[      3.16] L2 OILSEPARATORASSEMBLYDRAWING                                                             printed_ref=P1-REF-2012-123-009
[      3.17] L2 SUCTIONFILTERDATASHEET                                                                  printed_ref=P1-REF-DSS-12-123-018
[      3.18] L2 SUCTIONFILTERASSEMBLYDRAWING                                                            printed_ref=P1-REF-2012-123-011
[      3.19] L2 OILFILTERDATASHEET                                                                      printed_ref=P1-REF-DSS-12-123-015

====================================================================================================
TOC REGION 2
====================================================================================================
pages: [188]

## 11. Inspect page-level TOC reasoning

The objective is to make the detector explain itself.

For interesting pages we want to see:

```text
positive evidence
negative evidence
extraction source
score / confidence
final decision
```

Use the actual public API exposed by the installed `TOCDetector`.

In [11]:
print("TOCDetector public methods:")
for name in dir(toc_detector):
    if not name.startswith("_"):
        print(" ", name)

TOCDetector public methods:
  analyze_page
  detect_printed_tocs
  explain_page
  toc_score_threshold

In [ ]:
if hasattr(toc_detector, "analyze_page"):
    for page_number in FOCUS_PAGES:
        if 1 <= page_number <= len(pages_meta):
            result = toc_detector.analyze_page(pages_meta[page_number - 1])
            print()
            print(f"PAGE {page_number} TOC ANALYSIS")
            dump_object(result)
else:
    print("No public analyze_page() method in this version.")
    print("Inspect the returned TOCRegion objects from detect_printed_tocs().")

====================================================================================================
PAGE 6 TOC ANALYSIS
====================================================================================================
page_number: 6
is_toc: True
confidence: 0.5
evidence: {'positive': {'strong_toc_keywords': [], 'document_register_header': True, 'section_structure': {'match_count': 0, 'ratio': 0.0}, 'page_references': {'match_count': 0, 'ratio': 0.0}, 'dot_leaders': {'match_count': 0, 'ratio': 0.0}, 'toc_tables': [{'rows': 26, 'columns': 3, 'bbox': (47.15196990966797, 138.03709411621094, 547.2897033691406, 458.71401596069336), 'extraction_method': 'pymupdf', 'sample_rows': [['', 'Description', 'Doc. No.'], ['5.4', 'MAIN\x02MOTOR\x02TERMINAL\x02BOXES', 'P1-REF-2012-123-030'], ['5.5', 'MAIN\x02MOTOR\x02TESTING\x02PROCEDURE', 'P1-REF-PRD-12-123-006'], ['5.6', 'FAN\x02MOTORS\x02DRAWING', 'P1-REF-2012-123-024'], ['5.7', 'FAN\x02MOTORS\x02DATA\x02SHEET\x02&\x02CURVES', 'P1-REF-DSS-12-123-019']]}], 'toc_table_count': 1, 'entry_like_structure': {'line_count': 76, 'short_line_ratio': 1.0}, 'layout_consistency': {'consistent_entry_structure': False, 'page_reference_ratio': 0.0}}, 'negative': {'ambiguous_keywords': [], 'index_like_structure': {'score': 0.0, 'alphabetic_entry_ratio': 0.0, 'comma_page_ratio': 0.0, 'is_index_like': False}, 'data_table_structure': {'data_table_count': 0, 'tables': []}, 'prose_dominance': {'ratio': 0.0, 'long_sentence_count': 0}, 'insufficient_structure': {'is_insufficient': False, 'reason': None}}}
entries: [TOCEntry(text='MAIN\x02MOTOR\x02TERMINAL\x02BOXES', section_number='5.4', level=2, printed_page_ref='P1-REF-2012-123-030', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='MAIN\x02MOTOR\x02TESTING\x02PROCEDURE', section_number='5.5', level=2, printed_page_ref='P1-REF-PRD-12-123-006', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='FAN\x02MOTORS\x02DRAWING', section_number='5.6', level=2, printed_page_ref='P1-REF-2012-123-024', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='FAN\x02MOTORS\x02DATA\x02SHEET\x02&\x02CURVES', section_number='5.7', level=2, printed_page_ref='P1-REF-DSS-12-123-019', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='PUMP\x02MOTORS\x02DRAWING', section_number='5.8', level=2, printed_page_ref='P1-REF-2012-123-025', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='PUMP\x02MOTORS\x02DATA\x02SHEET\x02&\x02CURVES', section_number='5.9', level=2, printed_page_ref='P1-REF-DSS-12-123-020', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='PIPING', section_number='6', level=1, printed_page_ref=None, reference_kind=None, source_page=6, confidence=0.8), TOCEntry(text='LINE\x02LIST', section_number='6.1', level=2, printed_page_ref='P1-REF-LST-12-123-008', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='PIPING\x02TESTING\x02PROCEDURE', section_number='6.2', level=2, printed_page_ref='P1-REF-PRD-12-123-014', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='PIPING\x02CLASS', section_number='6.3', level=2, printed_page_ref='P1-REF-SPC-12-123-001', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='INSTRUMENTATION\x02&\x02CONTROL', section_number='7', level=1, printed_page_ref=None, reference_kind=None, source_page=6, confidence=0.8), TOCEntry(text='CONTROL\x02SYSTEM\x02BLOCK\x02DIAGRAM', section_number='7.1', level=2, printed_page_ref='P1-REF-2012-123-017', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='INSTRUMENT\x02LIST\x02&\x02SETTING', section_number='7.2', level=2, printed_page_ref='P1-REF-LST-12-123-005', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='INSTRUMENT\x02DATA\x02SHEETS', section_number='7.3', level=2, printed_page_ref='P1-REF-DSS-12-123-002', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='INSTRUMENT\x02HOOK\x02UP', section_number='7.4', level=2, printed_page_ref='P1-REF-2012-123-028', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='ELECTRICAL\x02HOOK\x02UP', section_number='7.5', level=2, printed_page_ref='P1-REF-2012-123-031', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='SAFETY\x02VALVES\x02CALCULATION\x02SHEETS', section_number='7.6', level=2, printed_page_ref='P1-REF-RCA-12-123-003', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='CAUSE\x02&\x02EFFECTS\x02CHART', section_number='7.7', level=2, printed_page_ref='P1-REF-LST-12-123-011', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='PACKAGE\x02I/O\x02LIST', section_number='7.8', level=2, printed_page_ref='P1-REF-LST-12-123-006', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='CABLES\x02LIST', section_number='7.9', level=2, printed_page_ref='P1-REF-LST-12-123-004', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='LOCAL\x02GAUGE\x02BOARD\x02&\x02JB\x02LAY\x02OUT', section_number='7.10', level=2, printed_page_ref='P1-REF-2012-123-018', reference_kind='doc_code', source_page=6, confidence=0.8), TOCEntry(text='INSTRUMENTS\x02AND\x02CABLE\x02TRAY\x02LAY\x03OUT', section_number='7.11', level=2, printed_page_ref='P1-REF-2012-123-004', reference_kind='doc_code', source_page=6, confidence=0.8)]
extraction_source: table

====================================================================================================
PAGE 7 TOC ANALYSIS
====================================================================================================
page_number: 7
is_toc: False
confidence: 0.35
evidence: {'positive': {'strong_toc_keywords': [], 'document_register_header': False, 'section_structure': {'match_count': 1, 'ratio': 0.04}, 'page_references': {'match_count': 1, 'ratio': 0.04}, 'dot_leaders': {'match_count': 0, 'ratio': 0.0}, 'toc_tables': [{'rows': 5, 'columns': 7, 'bbox': (21.02169282095773, 47.75202941894531, 573.3252563476562, 793.5490519205729), 'extraction_method': 'pymupdf', 'sample_rows': [['', None, 'CLIENT:\nPROJ.N°:\nPLANT:', 'OCP - MAROC PHOSPHORE\nQ3600XXX\nODI at P1 SITE\nN°2 AMMONIA STORAGE TANKS\nJORF LASFAR - MOROCCO', 'Vendor Job.N°:\nUnit:\nOCP Doc. Code:\nVendor Doc.No.:', '2012-123\n455A\n455A-REF-PRD- 009\nP1-REF-PRD-12-123-009', None], ['', None, 'LOCATION:', None, 'Sheet 1 of 1\nREV. 0', None, None], ['OCP - MAROC PHOSPHORE', None, None, None, None, None, None], ['', '1. GENERAL DOCUMENTS', None, None, None, None, ''], ['', None, None, None, None, None, None]]}], 'toc_table_count': 1, 'entry_like_structure': {'line_count': 25, 'short_line_ratio': 1.0}, 'layout_consistency': {'consistent_entry_structure': False, 'page_reference_ratio': 0.04}}, 'negative': {'ambiguous_keywords': [], 'index_like_structure': {'score': 0.0, 'alphabetic_entry_ratio': 0.0, 'comma_page_ratio': 0.0, 'is_index_like': False}, 'data_table_structure': {'data_table_count': 0, 'tables': []}, 'prose_dominance': {'ratio': 0.0, 'long_sentence_count': 0}, 'insufficient_structure': {'is_insufficient': False, 'reason': None}}}
entries: []
extraction_source: None

====================================================================================================
PAGE 187 TOC ANALYSIS
====================================================================================================
page_number: 187
is_toc: False
confidence: 0.0
evidence: {'positive': {'strong_toc_keywords': [], 'document_register_header': False, 'section_structure': {'match_count': 0, 'ratio': 0.0}, 'page_references': {'match_count': 1, 'ratio': 0.037037037037037035}, 'dot_leaders': {'match_count': 0, 'ratio': 0.0}, 'toc_tables': [], 'toc_table_count': 0, 'entry_like_structure': {'line_count': 27, 'short_line_ratio': 1.0}, 'layout_consistency': {'consistent_entry_structure': False, 'page_reference_ratio': 0.037037037037037035}}, 'negative': {'ambiguous_keywords': [], 'index_like_structure': {'score': 0.0, 'alphabetic_entry_ratio': 0.0, 'comma_page_ratio': 0.0, 'is_index_like': False}, 'data_table_structure': {'data_table_count': 1, 'tables': [{'rows': 5, 'columns': 7, 'bbox': (21.02169282095773, 47.75202941894531, 573.3252563476562, 793.5490519205729), 'extraction_method': 'pymupdf', 'sample_rows': [['', None, 'CLIENT:\nPROJ.N°:\nPLANT:', 'OCP - MAROC PHOSPHORE\nQ3600XXX\nODI at P1 SITE\nN°2 AMMONIA STORAGE TANKS\nJORF LASFAR - MOROCCO', 'Vendor Job.N°:\nUnit:\nOCP Doc. Code:\nVendor Doc.No.:', '2012-123\n455A\n455A-REF-PRD- 009\nP1-REF-PRD-12-123-009', None], ['', None, 'LOCATION:', None, 'Sheet 1 of 1\nREV. 0', None, None], ['OCP - MAROC PHOSPHORE', None, None, None, None, None, None], ['', 'INSTALLATION\nOPERATION\nAND MAINTENANCE', None, None, None, None, ''], ['', None, None, None, None, None, None]]}]}, 'prose_dominance': {'ratio': 0.0, 'long_sentence_count': 0}, 'insufficient_structure': {'is_insufficient': False, 'reason': None}}}
entries: []
extraction_source: None

## 12. Expected reasoning output

A useful diagnostic should be interpretable approximately as:

```text
PAGE 187

TOC = TRUE
confidence = 0.84

POSITIVE
  + TOC-like table
  + repeated section numbering
  + many page references
  + aligned title/reference columns

NEGATIVE
  - title is not an explicit TOC keyword
  - weak dot-leader evidence

EXTRACTION
  source = table
```

The important part is **evidence**, not the exact numeric score.

## 13. Negative cases: Index and ordinary tables

Explicitly test pages that look TOC-like but should not become TOCs.

Examples:

- `Index`;
- figure/table lists;
- ordinary engineering data tables;
- pages with many page references but no hierarchy;
- warning/notice pages.

This protects against the simplistic rule:

```text
many page references = TOC
```

In [ ]:
NEGATIVE_CASE_PAGES = []

for page_number in NEGATIVE_CASE_PAGES:
    if 1 <= page_number <= len(pages_meta):
        page = pages_meta[page_number - 1]
        text = get_attr(page, "raw_text", "text", default="") or ""
        tables = get_attr(page, "tables", "extracted_tables", default=[]) or []
        print()
        print(f"NEGATIVE CASE PAGE {page_number}")
        print(text[:5000])
        print("tables:", len(tables))

## 14. Title candidates and structure analyzer

TOC detection and title detection are separate.

Title candidates should combine typography/layout with semantic and structural evidence. A large font alone is not sufficient because covers, labels and other artifacts can also be large.

In [14]:
from src.document_structure.analyzer import DocumentSegmenter

analyzer = DocumentSegmenter()

print("DocumentSegmenter public methods:")
for name in dir(analyzer):
    if not name.startswith("_"):
        try:
            member = getattr(analyzer, name)
            if callable(member):
                print(f"  {name}{inspect.signature(member)}")
        except (TypeError, ValueError):
            print(" ", name)

DocumentSegmenter public methods:
  segment(pages: 'list[PageRepresentation]', toc_analyses: 'list[TOCAnalysis] | None' = None, title_candidates: 'dict[int, list[TitleCandidate]] | None' = None) -> 'list[DocumentSegment]'

## 15. Run the actual orchestration API

Do not guess the method signature. Inspect it above, then set the exact method name used by the current source.

In [15]:
STRUCTURE_METHOD_NAME = "segment"

if STRUCTURE_METHOD_NAME is not None:
    structure_method = getattr(analyzer, STRUCTURE_METHOD_NAME)
    print("Method:", STRUCTURE_METHOD_NAME)
    print("Signature:", inspect.signature(structure_method))

    # DocumentSegmenter.segment() wants the per-page TOCAnalysis list
    # (not the grouped TOCRegion list from section 9) -- recompute it
    # here since detect_printed_tocs() doesn't expose it directly.
    toc_analyses = [toc_detector.analyze_page(page) for page in pages_meta]

    segments = analyzer.segment(pages_meta, toc_analyses=toc_analyses)

    print("\nSegments found:", len(segments))
    for seg in segments[:30]:
        print(
            f"pages {seg.start_page:>4}-{seg.end_page:<4} "
            f"({seg.page_count:>4}p) source={seg.source:<12} "
            f"confidence={seg.confidence:.2f}  {seg.title or ''}"
        )
else:
    print("Set STRUCTURE_METHOD_NAME after inspecting the available methods.")

Method: segment
Signature: (pages: 'list[PageRepresentation]', toc_analyses: 'list[TOCAnalysis] | None' = None, title_candidates: 'dict[int, list[TitleCandidate]] | None' = None) -> 'list[DocumentSegment]'

Segments found: 69
pages    0-0    (   1p) source=toc          confidence=0.90  Mechanical Part Support & Fan Guard
pages    1-1    (   1p) source=toc          confidence=0.90  Introduction…………………...................................
pages    2-2    (   1p) source=toc          confidence=0.90  Namepalte Drawing
pages    3-3    (   1p) source=toc          confidence=0.90  INTRODUCTION ................................................................................................................................................
pages    4-4    (   1p) source=toc          confidence=0.90  INSTRUCTIONS POUR LE STOCKAGE ...................................................................................................................
pages    5-6    (   2p) source=toc          confidence=0.90  455AKR02 / 455AAR02
pages    7-7    (   1p) source=toc          confidence=0.90  Inspection des matériels sur la zone de stockage avant le montage .........................................................
pages    8-8    (   1p) source=toc          confidence=0.90  INSTRUCTIONS POUR LE TRANSPORT ET LE SOULEVEMENT ................................................................................
pages    9-13   (   5p) source=toc          confidence=0.90  Raisons d’ajuster le Vi…………………...............
pages   14-14   (   1p) source=toc          confidence=0.90  EQUIPEMENTS ET OUTILS SPECIAUX .................................................................................................................
pages   15-15   (   1p) source=toc          confidence=0.90  PROCEDURE DE MONTAGE ...............................................................................................................................
pages   16-16   (   1p) source=toc          confidence=0.90  D6 112
pages   17-17   (   1p) source=toc          confidence=0.90  CONNEXIONS ...................................................................................................................................................
pages   18-18   (   1p) source=toc          confidence=0.90  PROCEDURE DE PRE-COMMISSIONING .............................................................................................................
pages   19-19   (   1p) source=toc          confidence=0.90  PROCEDURE DE COMMISSIONING .....................................................................................................................
pages   20-20   (   1p) source=toc          confidence=0.90  CONTROLES PERIODIQUES ...............................................................................................................................
pages   21-21   (   1p) source=toc          confidence=0.90  LUBRIFICATION .............................................................................................................................................
pages   22-22   (   1p) source=toc          confidence=0.90  Befestigung von Teilen (Lagerschildern, Innendeckeln usw. )
pages   23-23   (   1p) source=toc          confidence=0.90  INSTRUCTIONS D’ENTRETIEN .................................................................................................................
pages   24-24   (   1p) source=toc          confidence=0.90  NETTOYAGE INTERIEUR DES TUBES ..............................................................................................................
pages   25-25   (   1p) source=toc          confidence=0.90  FUITE DU JOINT DE BOUCHONS .....................................................................................................................
pages   26-26   (   1p) source=toc          confidence=0.90  BOUCHAGE DES TUBES ENDOMMAGES ..........................................................................................................
pages   27-27   (   1p) source=toc          confidence=0.90  ESSAI HYDRAULIQUE ....................................................................................................................................
pages   28-38   (  11p) source=toc          confidence=0.90  D6 71
pages   39-39   (   1p) source=toc          confidence=0.90  délestage
pages   40-45   (   6p) source=toc          confidence=0.90  -
pages   46-55   (  10p) source=toc          confidence=0.90  principal………...............…
pages   56-58   (   3p) source=toc          confidence=0.90  capacité………………………..............……..……
pages   59-60   (   2p) source=toc          confidence=0.90  Ecrous de blocage...................................……
pages   61-61   (   1p) source=toc          confidence=0.90  Liste des joints toriques..……………………........…

## 16. Bookmarks ↔ detected structure

Compare the PDF-native outline with printed TOCs and title candidates.

Agreement is strong evidence. Disagreement is not necessarily a failure: PDFs can contain incomplete, stale or missing bookmarks.

In [16]:
bookmark_df = pd.DataFrame([
    {"level": item[0], "title": item[1], "pdf_page": item[2]}
    for item in outline
])

display(bookmark_df.head(30))

Empty DataFrame
Columns: []
Index: []

## 17. Document boundaries

A TOC is **not automatically a document boundary**.

Boundary evidence can include:

- large/top-of-page title;
- document-type wording;
- cover-like layout;
- document identifier;
- manufacturer change;
- page-numbering change;
- major layout change;
- following TOC.

Nested/local TOCs must therefore be treated differently from a new embedded document.

## 18. Nested/local TOCs

A large PDF can have:

```text
global TOC
  ↓
section
  ↓
local TOC
  ↓
subsections
```

Therefore:

```text
TOC detected ≠ split document
```

The decision needs surrounding context and hierarchy.

## 19. Hierarchy and page ranges

The target is a structure such as:

```text
Document
├── 1 Introduction
│   ├── 1.1 Scope
│   └── 1.2 Safety
├── 2 Installation
└── 3 Maintenance
```

Then infer page ranges while keeping:

- printed page references;
- PDF page indices;
- hierarchy level;
- provenance;
- confidence

as separate concepts.

## 20. Structure → downstream routing

This is the main reason for the entire structure layer.

Instead of:

```text
500 pages → expensive LLM / NER / OCR on every page
```

we want:

```text
500 pages
  ↓
cheap extraction + structural analysis
  ↓
document architecture
  ↓
useful sections/pages
  ↓
expensive extraction only where justified
```

The goal is **high useful-page recall with substantial computational savings**.

In [17]:
toc_pages = sorted({
    page
    for region in detected_tocs
    for page in region.page_numbers
})

print("Total PDF pages:", len(pages_meta))
print("Detected TOC pages:", toc_pages)
if pages_meta:
    print("TOC-page fraction:", f"{len(toc_pages) / len(pages_meta):.1%}")

Total PDF pages: 1068
Detected TOC pages: [5, 6, 188, 282, 283, 284, 285, 409, 549, 554, 599, 601, 603, 635, 636, 751, 753, 776, 794, 876, 938, 1000, 1068]
TOC-page fraction: 2.2%