# TOC -> OCR (tables) -> LLM #1 (pipeline réel, pas de données synthétiques)

Ce notebook chaîne, sur un **vrai PDF**, exactement dans le style de
`04_document_structure_analysis.ipynb` (mêmes classes, mêmes appels réels,
pas de reconstruction/synthèse) :

```text
PDF réel
  -> PageAnalyzer (src/document_structure/page_analysis.py)
  -> TOCDetector.detect_printed_tocs (src/document_structure/toc.py)      [TOC détecté]
  -> OCR table (src/ocr/ocr_pipeline.py) sur les pages du TOC             [re-extraction]
  -> fusion native + OCR -> contenu organisé par région de TOC
  -> classify_sections (src/llm/classifier.py) -- une fois par TOC détecté
```

Rien n'est réécrit : chaque étape appelle le code du projet tel quel.

## 0. Configuration -- même PDF que le notebook de référence

In [24]:
from pathlib import Path
import sys
import json as json_lib

import pandas as pd

import pymupdf as fitz

sys.path.insert(
    0,
    r"C:\Users\camelia\Downloads\last version 3"
    
)

PDF_PATH = r"C:\Users\camelia\Downloads\projets\projet1OCP\data\MYCOM Operating and Maintenance Manual Refrigeration Unit (1).pdf"


print("PDF_PATH:", PDF_PATH)

PDF_PATH: C:\Users\camelia\Downloads\projets\projet1OCP\data\MYCOM Operating and Maintenance Manual Refrigeration Unit (1).pdf

## 1. PageAnalyzer -- extraction native (texte + tables), inchangé

In [2]:
from src.document_structure.page_analysis import PageAnalyzer

doc = fitz.open(str(PDF_PATH))
page_analyzer = PageAnalyzer()
pages_meta = page_analyzer.extract_document(doc)

print("Pages analysées :", len(pages_meta))

warning: The `fitz` API is deprecated and will be removed in future. Use `import pymupdf` instead.
Consider using the pymupdf_layout package for a greatly improved page layout analysis.
Pages analysées : 1068

## 2. TOCDetector -- détection réelle du/des Table of Contents

Exactement `detect_printed_tocs()`, comme dans le notebook de référence
(section 9). C'est la LISTE DE VRAIES `TOCRegion` qu'on va ensuite traiter
une par une.

In [3]:
from src.document_structure.toc import TOCDetector

toc_detector = TOCDetector()
detected_tocs = toc_detector.detect_printed_tocs(pages_meta)

print("TOC détectés :", len(detected_tocs))
for i, region in enumerate(detected_tocs, 1):
    print(f"  region {i}: pages={region.page_numbers} type={region.toc_type} "
          f"confidence={round(region.confidence, 3)} entries={len(region.entries)}")

TOC détectés : 5
  region 1: pages=[5, 6] type=printed confidence=0.5 entries=69
  region 2: pages=[188] type=printed confidence=0.5 entries=36
  region 3: pages=[409] type=printed confidence=0.71 entries=77
  region 4: pages=[635] type=printed confidence=0.5 entries=3
  region 5: pages=[794] type=printed confidence=0.621 entries=31

## 3. Transformer chaque page en image, puis appliquer le pipeline OCR

Le pipeline OCR du projet (`src/ocr/ocr_pipeline.py`) travaille sur une
**image** (tableau numpy), pas directement sur le PDF. On rend donc les
deux étapes explicites, dans l'ordre :

1. **page PDF -> image** : `load_pdf_page_as_image()` (`src/ocr/preprocessing.py`,
   déjà utilisé par `OCRPipeline.process()` en interne -- on l'appelle ici
   nous-mêmes pour voir l'image intermédiaire) rend la page en image OpenCV
   BGR via PyMuPDF (`get_pixmap`), au DPI du projet (`DEFAULT_DPI`).
2. **image -> pipeline OCR** : on enchaîne alors, sur CETTE image, les
   étapes du pipeline telles qu'exposées par `OCRPipeline`
   (`detect_tables` -> `recognize_table_structure` -> `ocr_cells` ->
   `reconstruct_table`) -- ce sont exactement les étapes internes de
   `OCRPipeline.process()`, simplement rendues explicites ici pour
   inspecter chaque résultat intermédiaire (table détectée, cellules,
   DataFrame reconstruit).

Le DataFrame obtenu est ensuite reparsé avec `TOCDetector._parse_table()`
-- le même parseur que pour une table native, pas de logique dupliquée.

Si `paddleocr` n'est pas installé (`OCRUnavailableError`) ou si l'OCR
échoue sur une page donnée, on le signale et on continue avec les seules
entrées natives pour cette page -- une page ne doit jamais faire échouer
tout le notebook (même principe de dégradation gracieuse que
`pipeline/page_processing.py`).

In [7]:
%pip cache purge

Files removed: 3880 (3775.4 MB)
Note: you may need to restart the kernel to use updated packages.

In [9]:
%rmdir /s /q "%USERPROFILE%\.paddlex\official_models"

In [10]:
%pip install paddlepaddle==3.2.2 paddleocr==3.3.0

Requirement already satisfied: paddlepaddle==3.2.2 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (3.2.2)
Collecting paddleocr==3.3.0
  Using cached paddleocr-3.3.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: httpx in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlepaddle==3.2.2) (0.28.1)
Requirement already satisfied: numpy>=1.21 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlepaddle==3.2.2) (2.3.5)
Requirement already satisfied: protobuf>=3.20.2 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlepaddle==3.2.2) (6.33.6)
Requirement already satisfied: Pillow in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlepaddle==3.2.2) (12.3.0)
Requirement already satisfied: opt-einsum==3.3.0 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlepaddle==3.2.2) (3.3.0)
Requirement already satisfied: networkx in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlepaddle==3.2.2) (3.5)
Requirement already satisfied: typing-extensions in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlepaddle==3.2.2) (4.16.0)
Requirement already satisfied: safetensors>=0.6.0 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlepaddle==3.2.2) (0.8.0)
Requirement already satisfied: paddlex<3.4.0,>=3.3.0 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (3.3.13)
Requirement already satisfied: PyYAML>=6 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddleocr==3.3.0) (6.0.2)
Requirement already satisfied: requests in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddleocr==3.3.0) (2.34.2)
Requirement already satisfied: aistudio-sdk>=0.3.5 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (0.3.8)
Requirement already satisfied: chardet in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (7.4.3)
Requirement already satisfied: colorlog in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (6.10.1)
Requirement already satisfied: filelock in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (3.18.0)
Requirement already satisfied: huggingface-hub in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (0.34.3)
Requirement already satisfied: modelscope>=1.28.0 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (1.38.1)
Requirement already satisfied: packaging in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (25.0)
Requirement already satisfied: pandas>=1.3 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (3.0.5)
Requirement already satisfied: prettytable in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (3.18.0)
Requirement already satisfied: py-cpuinfo in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (9.0.0)
Requirement already satisfied: pydantic>=2 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (2.13.4)
Requirement already satisfied: ruamel.yaml in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (0.19.1)
Requirement already satisfied: ujson in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (5.13.0)
Requirement already satisfied: imagesize in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (2.0.0)
Requirement already satisfied: opencv-contrib-python==4.10.0.84 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (4.10.0.84)
Requirement already satisfied: pyclipper in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (1.4.0)
Requirement already satisfied: pypdfium2>=4 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (5.11.0)
Requirement already satisfied: python-bidi in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (0.6.11)
Requirement already satisfied: shapely in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (2.1.2)
Requirement already satisfied: psutil in c:\users\camelia\appdata\roaming\python\python311\site-packages (from aistudio-sdk>=0.3.5->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (7.2.2)
Requirement already satisfied: tqdm in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from aistudio-sdk>=0.3.5->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (4.70.0)
Requirement already satisfied: bce-python-sdk in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from aistudio-sdk>=0.3.5->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (0.9.72)
Requirement already satisfied: click in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from aistudio-sdk>=0.3.5->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (8.2.1)
Requirement already satisfied: modelscope-hub>=0.0.7 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from modelscope>=1.28.0->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (0.1.7)
Requirement already satisfied: setuptools in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from modelscope>=1.28.0->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (84.0.0)
Requirement already satisfied: urllib3>=1.26 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from modelscope>=1.28.0->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.3->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.3->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from pydantic>=2->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from pydantic>=2->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from pydantic>=2->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (0.4.4)
Requirement already satisfied: six>=1.5 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from requests->paddleocr==3.3.0) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from requests->paddleocr==3.3.0) (3.10)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from requests->paddleocr==3.3.0) (2025.7.14)
Requirement already satisfied: colorama in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from tqdm->aistudio-sdk>=0.3.5->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (0.4.6)
Requirement already satisfied: pycryptodome>=3.8.0 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from bce-python-sdk->aistudio-sdk>=0.3.5->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (3.23.0)
Requirement already satisfied: future>=0.6.0 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from bce-python-sdk->aistudio-sdk>=0.3.5->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (1.0.0)
Requirement already satisfied: crc32c>=2.2.post0 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from bce-python-sdk->aistudio-sdk>=0.3.5->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (2.8)
Requirement already satisfied: anyio in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from httpx->paddlepaddle==3.2.2) (4.9.0)
Requirement already satisfied: httpcore==1.* in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from httpx->paddlepaddle==3.2.2) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from httpcore==1.*->httpx->paddlepaddle==3.2.2) (0.16.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from anyio->httpx->paddlepaddle==3.2.2) (1.3.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from huggingface-hub->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (2025.7.0)
Requirement already satisfied: wcwidth>=0.3.5 in c:\users\camelia\appdata\roaming\python\python311\site-packages (from prettytable->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (0.6.0)
Using cached paddleocr-3.3.0-py3-none-any.whl (81 kB)
Installing collected packages: paddleocr
Successfully installed paddleocr-3.3.0
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~addlex (c:\Users\camelia\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~addlex (c:\Users\camelia\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~addlex (c:\Users\camelia\AppData\Local\Programs\Python\Python311\Lib\site-packages)

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting paddlepaddle==3.2.2
  Downloading paddlepaddle-3.2.2-cp311-cp311-win_amd64.whl.metadata (8.7 kB)
Collecting paddleocr==3.3.0
  Downloading paddleocr-3.3.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: httpx in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlepaddle==3.2.2) (0.28.1)
Requirement already satisfied: numpy>=1.21 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlepaddle==3.2.2) (2.3.5)
Requirement already satisfied: protobuf>=3.20.2 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlepaddle==3.2.2) (6.33.6)
Requirement already satisfied: Pillow in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlepaddle==3.2.2) (12.3.0)
Requirement already satisfied: opt-einsum==3.3.0 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlepaddle==3.2.2) (3.3.0)
Requirement already satisfied: networkx in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlepaddle==3.2.2) (3.5)
Requirement already satisfied: typing-extensions in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlepaddle==3.2.2) (4.16.0)
Requirement already satisfied: safetensors>=0.6.0 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlepaddle==3.2.2) (0.8.0)
Collecting paddlex<3.4.0,>=3.3.0 (from paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0)
  Downloading paddlex-3.3.13-py3-none-any.whl.metadata (79 kB)
Requirement already satisfied: PyYAML>=6 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddleocr==3.3.0) (6.0.2)
Requirement already satisfied: requests in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddleocr==3.3.0) (2.34.2)
Requirement already satisfied: aistudio-sdk>=0.3.5 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (0.3.8)
Requirement already satisfied: chardet in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (7.4.3)
Requirement already satisfied: colorlog in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (6.10.1)
Requirement already satisfied: filelock in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (3.18.0)
Requirement already satisfied: huggingface-hub in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (0.34.3)
Requirement already satisfied: modelscope>=1.28.0 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (1.38.1)
Requirement already satisfied: packaging in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (25.0)
Requirement already satisfied: pandas>=1.3 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (3.0.5)
Requirement already satisfied: prettytable in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (3.18.0)
Requirement already satisfied: py-cpuinfo in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (9.0.0)
Requirement already satisfied: pydantic>=2 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (2.13.4)
Requirement already satisfied: ruamel.yaml in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (0.19.1)
Requirement already satisfied: ujson in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (5.13.0)
Requirement already satisfied: imagesize in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (2.0.0)
Requirement already satisfied: opencv-contrib-python==4.10.0.84 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (4.10.0.84)
Requirement already satisfied: pyclipper in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (1.4.0)
Requirement already satisfied: pypdfium2>=4 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (5.11.0)
Requirement already satisfied: python-bidi in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (0.6.11)
Requirement already satisfied: shapely in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (2.1.2)
Requirement already satisfied: psutil in c:\users\camelia\appdata\roaming\python\python311\site-packages (from aistudio-sdk>=0.3.5->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (7.2.2)
Requirement already satisfied: tqdm in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from aistudio-sdk>=0.3.5->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (4.70.0)
Requirement already satisfied: bce-python-sdk in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from aistudio-sdk>=0.3.5->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (0.9.72)
Requirement already satisfied: click in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from aistudio-sdk>=0.3.5->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (8.2.1)
Requirement already satisfied: modelscope-hub>=0.0.7 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from modelscope>=1.28.0->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (0.1.7)
Requirement already satisfied: setuptools in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from modelscope>=1.28.0->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (84.0.0)
Requirement already satisfied: urllib3>=1.26 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from modelscope>=1.28.0->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.3->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.3->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from pydantic>=2->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from pydantic>=2->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from pydantic>=2->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (0.4.4)
Requirement already satisfied: six>=1.5 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from requests->paddleocr==3.3.0) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from requests->paddleocr==3.3.0) (3.10)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from requests->paddleocr==3.3.0) (2025.7.14)
Requirement already satisfied: colorama in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from tqdm->aistudio-sdk>=0.3.5->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (0.4.6)
Requirement already satisfied: pycryptodome>=3.8.0 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from bce-python-sdk->aistudio-sdk>=0.3.5->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (3.23.0)
Requirement already satisfied: future>=0.6.0 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from bce-python-sdk->aistudio-sdk>=0.3.5->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (1.0.0)
Requirement already satisfied: crc32c>=2.2.post0 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from bce-python-sdk->aistudio-sdk>=0.3.5->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (2.8)
Requirement already satisfied: anyio in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from httpx->paddlepaddle==3.2.2) (4.9.0)
Requirement already satisfied: httpcore==1.* in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from httpx->paddlepaddle==3.2.2) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from httpcore==1.*->httpx->paddlepaddle==3.2.2) (0.16.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from anyio->httpx->paddlepaddle==3.2.2) (1.3.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\camelia\appdata\local\programs\python\python311\lib\site-packages (from huggingface-hub->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (2025.7.0)
Requirement already satisfied: wcwidth>=0.3.5 in c:\users\camelia\appdata\roaming\python\python311\site-packages (from prettytable->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr==3.3.0) (0.6.0)
Downloading paddlepaddle-3.2.2-cp311-cp311-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
    --------------------------------------- 1.6/101.7 MB 8.4 MB/s eta 0:00:12
   - -------------------------------------- 3.1/101.7 MB 9.7 MB/s eta 0:00:11
   - -------------------------------------- 4.2/101.7 MB 9.3 MB/s eta 0:00:11
   - -------------------------------------- 4.2/101.7 MB 9.3 MB/s eta 0:00:11
   -- ------------------------------------- 5.2/101.7 MB 5.5 MB/s eta 0:00:18
   -- ------------------------------------- 6.3/101.7 MB 4.9 MB/s eta 0:00:20
   --- ------------------------------------ 7.9/101.7 MB 5.3 MB/s eta 0:00:18
   --- ------------------------------------ 9.4/101.7 MB 5.8 MB/s eta 0:00:16
   ---- ----------------------------------- 11.5/101.7 MB 6.2 MB/s eta 0:00:15
   ----- ---------------------------------- 13.4/101.7 MB 6.4 MB/s eta 0:00:14
   ----- ---------------------------------- 14.7/101.7 MB 6.6 MB/s eta 0:00:14
   ------ --------------------------------- 16.8/101.7 MB 6.8 MB/s eta 0:00:13
   ------ --------------------------------- 16.8/101.7 MB 6.8 MB/s eta 0:00:13
   ------- -------------------------------- 18.9/101.7 MB 6.5 MB/s eta 0:00:13
   -------- ------------------------------- 20.7/101.7 MB 6.6 MB/s eta 0:00:13
   -------- ------------------------------- 22.5/101.7 MB 6.7 MB/s eta 0:00:12
   --------- ------------------------------ 24.1/101.7 MB 6.9 MB/s eta 0:00:12
   ---------- ----------------------------- 25.7/101.7 MB 6.9 MB/s eta 0:00:12
   ---------- ----------------------------- 27.3/101.7 MB 7.0 MB/s eta 0:00:11
   ----------- ---------------------------- 28.8/101.7 MB 6.9 MB/s eta 0:00:11
   ----------- ---------------------------- 30.4/101.7 MB 7.1 MB/s eta 0:00:11
   ------------ --------------------------- 32.5/101.7 MB 7.1 MB/s eta 0:00:10
   ------------- -------------------------- 33.6/101.7 MB 7.2 MB/s eta 0:00:10
   ------------- -------------------------- 34.6/101.7 MB 7.0 MB/s eta 0:00:10
   -------------- ------------------------- 36.4/101.7 MB 7.0 MB/s eta 0:00:10
   -------------- ------------------------- 37.7/101.7 MB 7.1 MB/s eta 0:00:10
   --------------- ------------------------ 39.8/101.7 MB 7.1 MB/s eta 0:00:09
   ---------------- ----------------------- 41.9/101.7 MB 7.2 MB/s eta 0:00:09
   ----------------- ---------------------- 43.5/101.7 MB 7.2 MB/s eta 0:00:09
   ----------------- ---------------------- 45.1/101.7 MB 7.3 MB/s eta 0:00:08
   ------------------ --------------------- 47.2/101.7 MB 7.3 MB/s eta 0:00:08
   ------------------- -------------------- 48.8/101.7 MB 7.3 MB/s eta 0:00:08
   ------------------- -------------------- 50.6/101.7 MB 7.4 MB/s eta 0:00:07
   -------------------- ------------------- 51.9/101.7 MB 7.3 MB/s eta 0:00:07
   --------------------- ------------------ 54.0/101.7 MB 7.4 MB/s eta 0:00:07
   --------------------- ------------------ 55.8/101.7 MB 7.4 MB/s eta 0:00:07
   ---------------------- ----------------- 57.1/101.7 MB 7.4 MB/s eta 0:00:07
   ----------------------- ---------------- 59.0/101.7 MB 7.4 MB/s eta 0:00:06
   ----------------------- ---------------- 60.8/101.7 MB 7.5 MB/s eta 0:00:06
   ------------------------ --------------- 62.9/101.7 MB 7.5 MB/s eta 0:00:06
   ------------------------- -------------- 65.0/101.7 MB 7.6 MB/s eta 0:00:05
   -------------------------- ------------- 66.6/101.7 MB 7.6 MB/s eta 0:00:05
   -------------------------- ------------- 68.2/101.7 MB 7.6 MB/s eta 0:00:05
   --------------------------- ------------ 70.3/101.7 MB 7.6 MB/s eta 0:00:05
   ---------------------------- ----------- 71.3/101.7 MB 7.7 MB/s eta 0:00:04
   ---------------------------- ----------- 72.9/101.7 MB 7.6 MB/s eta 0:00:04
   ----------------------------- ---------- 75.0/101.7 MB 7.6 MB/s eta 0:00:04
   ------------------------------ --------- 76.5/101.7 MB 7.7 MB/s eta 0:00:04
   ------------------------------ --------- 78.6/101.7 MB 7.7 MB/s eta 0:00:04
   ------------------------------- -------- 80.0/101.7 MB 7.6 MB/s eta 0:00:03
   -------------------------------- ------- 81.8/101.7 MB 7.7 MB/s eta 0:00:03
   -------------------------------- ------- 83.4/101.7 MB 7.7 MB/s eta 0:00:03
   --------------------------------- ------ 86.0/101.7 MB 7.7 MB/s eta 0:00:03
   ---------------------------------- ----- 87.8/101.7 MB 7.7 MB/s eta 0:00:02
   ----------------------------------- ---- 89.1/101.7 MB 7.8 MB/s eta 0:00:02
   ----------------------------------- ---- 91.2/101.7 MB 7.8 MB/s eta 0:00:02
   ------------------------------------ --- 93.3/101.7 MB 7.8 MB/s eta 0:00:02
   ------------------------------------- -- 95.4/101.7 MB 7.8 MB/s eta 0:00:01
   ------------------------------------- -- 96.5/101.7 MB 7.8 MB/s eta 0:00:01
   -------------------------------------- - 98.6/101.7 MB 7.8 MB/s eta 0:00:01
   ---------------------------------------  100.7/101.7 MB 7.9 MB/s eta 0:00:01
   ---------------------------------------  101.7/101.7 MB 7.9 MB/s eta 0:00:01
   ---------------------------------------  101.7/101.7 MB 7.9 MB/s eta 0:00:01
   ---------------------------------------  101.7/101.7 MB 7.9 MB/s eta 0:00:01
   ---------------------------------------  101.7/101.7 MB 7.9 MB/s eta 0:00:01
   ---------------------------------------  101.7/101.7 MB 7.9 MB/s eta 0:00:01
   ---------------------------------------  101.7/101.7 MB 7.9 MB/s eta 0:00:01
   ---------------------------------------  101.7/101.7 MB 7.9 MB/s eta 0:00:01
   ---------------------------------------  101.7/101.7 MB 7.9 MB/s eta 0:00:01
   ---------------------------------------  101.7/101.7 MB 7.9 MB/s eta 0:00:01
   ---------------------------------------  101.7/101.7 MB 7.9 MB/s eta 0:00:01
   ---------------------------------------  101.7/101.7 MB 7.9 MB/s eta 0:00:01
   ---------------------------------------- 101.7/101.7 MB 6.7 MB/s  0:00:15
Downloading paddleocr-3.3.0-py3-none-any.whl (81 kB)
Downloading paddlex-3.3.13-py3-none-any.whl (1.9 MB)
   ---------------------------------------- 0.0/1.9 MB ? eta -:--:--
   ---------------------------------------- 1.9/1.9 MB 12.8 MB/s  0:00:00
Installing collected packages: paddlepaddle, paddlex, paddleocr

   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]
   ---------------------------------------- 0/3 [paddlepaddle]

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
!{sys.executable} -m pip show paddleocr

Name: paddleocr
Version: 3.3.0
Summary: Awesome multilingual OCR and document parsing toolkits based on PaddlePaddle
Home-page: https://github.com/PaddlePaddle/PaddleOCR
Author:
Author-email: PaddlePaddle <paddleocr@baidu.com>
License: Apache License 2.0
Location: c:\Users\camelia\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires: paddlex, PyYAML, requests, typing-extensions
Required-by:

In [4]:
import numpy as np

from src.document_structure.models import TableRepresentation
from src.ocr.preprocessing import load_pdf_page_as_image
from src.ocr.config import DEFAULT_DPI


def render_page_as_image(pdf_path, pdf_page_number: int, dpi: int = DEFAULT_DPI) -> np.ndarray:
    """Etape 1 : page PDF (1-indexee) -> image OpenCV BGR.
    Meme fonction que celle utilisee en interne par OCRPipeline.process()
    (src/ocr/preprocessing.py), appelee ici explicitement."""
    return load_pdf_page_as_image(str(pdf_path), page_number=pdf_page_number - 1, dpi=dpi)


def run_ocr_pipeline_on_image(ocr_pipeline, image: np.ndarray) -> pd.DataFrame:
    """Etape 2 : image -> pipeline OCR, en reproduisant explicitement les
    etapes internes de OCRPipeline.process() (detection de layout -> table
    dominante -> structure de table -> OCR par cellule -> reconstruction),
    pour pouvoir inspecter chaque etape intermediaire."""
    tables = ocr_pipeline.detect_tables(image)
    if not tables:
        return pd.DataFrame()

    table = tables[0]  # table dominante de la page
    coordinate = table.get("coordinate", table.get("bbox"))
    x1, y1, x2, y2 = map(int, coordinate)
    table_image = image[y1:y2, x1:x2]

    structure = ocr_pipeline.recognize_table_structure(table_image)

    # Les coordonnees des cellules sont relatives a table_image -> les
    # replacer dans le repere de l'image complete de la page.
    for cell in structure["cells"]:
        cell["bbox"][0] += x1
        cell["bbox"][1] += y1
        cell["bbox"][2] += x1
        cell["bbox"][3] += y1
        cell["cx"] += x1
        cell["cy"] += y1

    cells = ocr_pipeline.ocr_cells(image, structure["cells"])
    return ocr_pipeline.reconstruct_table(cells)


def ocr_table_entries_for_page(pdf_path, pdf_page_number: int):
    """Chaine complete : page -> image -> pipeline OCR -> DataFrame ->
    TOCEntry (via le meme parseur que les tables natives)."""
    try:
        from src.ocr.ocr_pipeline import  OCRPipeline
    except Exception as exc:
        print(f"  [page {pdf_page_number}] OCR indisponible (import) : {exc}")
        return []

    try:
        ocr_pipeline = OCRPipeline()
        image = render_page_as_image(pdf_path, pdf_page_number)
        print(f"  [page {pdf_page_number}] image rendue : {image.shape[1]}x{image.shape[0]}px")
        df = run_ocr_pipeline_on_image(ocr_pipeline, image)
    except Exception as exc:
        print(f"  [page {pdf_page_number}] OCR table a echoue : {exc}")
        return []

    if df is None or df.empty:
        print(f"  [page {pdf_page_number}] OCR : aucune table reconstruite")
        return []

    table = TableRepresentation(
        rows=[list(df.columns)] + df.values.tolist(),
        extraction_method="paddleocr",
    )
    return toc_detector._parse_table(table, source_page=pdf_page_number)


def ocr_text_for_page(pdf_path, pdf_page_number: int) -> str:
    """Meme fonction que pipeline/page_processing.py pour le texte OCR
    plein-page (Tesseract)."""
    try:
        from src.ocr.text_ocr import ocr_pdf_page_text
        return ocr_pdf_page_text(str(pdf_path), page_number=pdf_page_number - 1)
    except Exception as exc:
        print(f"  [page {pdf_page_number}] OCR texte a echoue : {exc}")
        return ""


# Appliquer l'OCR table sur toutes les pages de tous les TOC detectes.
ocr_entries_by_region = []
for i, region in enumerate(detected_tocs, 1):
    print(f"\n--- Region {i} (pages {region.page_numbers}) ---")
    region_ocr_entries = []
    for pdf_page in region.page_numbers:
        entries = ocr_table_entries_for_page(PDF_PATH, pdf_page)
        print(f"  page {pdf_page}: {len(entries)} entree(s) via OCR table")
        region_ocr_entries.extend(entries)
    ocr_entries_by_region.append(region_ocr_entries)

--- Region 1 (pages [5, 6]) ---

c:\Users\camelia\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Checking connectivity to the model hosters, this may take a while. To bypass this check, set `DISABLE_MODEL_SOURCE_CHECK` to `True`.
c:\Users\camelia\AppData\Local\Programs\Python\Python311\Lib\site-packages\paddle\utils\cpp_extension\extension_utils.py:718: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\camelia\.paddlex\official_models\PP-DocLayout_plus-L`.
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\camelia\.paddlex\official_models\SLANet`.
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\camelia\.paddlex\official_models\PP-OCRv5_server_rec`.
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\camelia\.paddlex\official_models\PP-DocLayout_plus-L`.
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\camelia\.paddlex\official_models\SLANet`.
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\camelia\.paddlex\official_models\PP-OCRv5_server_rec`.

  [page 5] image rendue : 2481x3509px

Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\camelia\.paddlex\official_models\PP-DocLayout_plus-L`.

  page 5: 26 entree(s) via OCR table

Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\camelia\.paddlex\official_models\SLANet`.
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\camelia\.paddlex\official_models\PP-OCRv5_server_rec`.

  [page 6] image rendue : 2481x3509px

Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\camelia\.paddlex\official_models\PP-DocLayout_plus-L`.

  page 6: 23 entree(s) via OCR table

--- Region 2 (pages [188]) ---

Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\camelia\.paddlex\official_models\SLANet`.
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\camelia\.paddlex\official_models\PP-OCRv5_server_rec`.

  [page 188] image rendue : 2481x3509px

Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\camelia\.paddlex\official_models\PP-DocLayout_plus-L`.

  page 188: 23 entree(s) via OCR table

--- Region 3 (pages [409]) ---

Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\camelia\.paddlex\official_models\SLANet`.
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\camelia\.paddlex\official_models\PP-OCRv5_server_rec`.

  [page 409] image rendue : 2481x3509px

Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\camelia\.paddlex\official_models\PP-DocLayout_plus-L`.

  [page 409] OCR : aucune table reconstruite
  page 409: 0 entree(s) via OCR table

--- Region 4 (pages [635]) ---

Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\camelia\.paddlex\official_models\SLANet`.
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\camelia\.paddlex\official_models\PP-OCRv5_server_rec`.

  [page 635] image rendue : 2481x3509px

Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\camelia\.paddlex\official_models\PP-DocLayout_plus-L`.

  page 635: 9 entree(s) via OCR table

--- Region 5 (pages [794]) ---

Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\camelia\.paddlex\official_models\SLANet`.
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\camelia\.paddlex\official_models\PP-OCRv5_server_rec`.

  [page 794] image rendue : 2481x3509px
  [page 794] OCR : aucune table reconstruite
  page 794: 0 entree(s) via OCR table

## 4. Organiser : fusionner entrées natives + entrées OCR par région

Pour chaque `TOCRegion`, on combine `region.entries` (natif,
`TOCDetector`/PyMuPDF) et les entrées OCR équivalentes, en dédupliquant sur
le texte du titre -- on garde la version native quand elle existe (elle
vient d'un vrai texte/table PDF), et on ajoute les entrées supplémentaires
que seul l'OCR a trouvées.

In [22]:
def organize_region(region, ocr_entries):
    seen_titles = {e.text.strip().lower() for e in region.entries if e.text}
    merged = list(region.entries)
    added_from_ocr = 0
    for entry in ocr_entries:
        key = (entry.text or "").strip().lower()
        if key and key not in seen_titles:
            merged.append(entry)
            seen_titles.add(key)
            added_from_ocr += 1
    return merged, added_from_ocr


organized_regions = []
for i, (region, ocr_entries) in enumerate(zip(detected_tocs, ocr_entries_by_region), 1):
    merged, added = organize_region(region, ocr_entries)
    organized_regions.append(merged)
    print(f"Region {i}: {len(region.entries)} natives + {added} ajoutees par OCR = {len(merged)} au total")

# Inspection : la region la plus fournie
if organized_regions:
    biggest = max(range(len(organized_regions)), key=lambda i: len(organized_regions[i]))
    print(f"\nRegion {biggest + 1} (la plus fournie), premieres entrees organisees :")
    df_preview = pd.DataFrame([e.to_dict() for e in organized_regions[biggest][::]])
    pd.set_option('display.max_rows', None)
    pd.set_option('display.max_columns', None)
    display(df_preview.head(100))

Region 1: 69 natives + 49 ajoutees par OCR = 118 au total
Region 2: 36 natives + 22 ajoutees par OCR = 58 au total
Region 3: 77 natives + 0 ajoutees par OCR = 77 au total
Region 4: 3 natives + 9 ajoutees par OCR = 12 au total
Region 5: 31 natives + 0 ajoutees par OCR = 31 au total

Region 1 (la plus fournie), premieres entrees organisees :

,text,section_number,level,printed_page_ref,reference_kind,source_page,confidence
0,DOCUMENTS&DRAWINGSLIST,1.1,2,P1-REF-LST-12-123-007,doc_code,5,0.8
1,SUBVENDORLIST,1.2,2,P1-REF-LST-12-123-003,doc_code,5,0.8
2,NOISEDATASHEET,1.3,2,P1-REF-DSS-12-123-008,doc_code,5,0.8
3,LUBRICANTLIST,1.4,2,P1-REF-SPC-12-123-002,doc_code,5,0.8
4,PAINTINGSPECIFICATIONS,1.5,2,P1-REF-SPC-12-123-003,doc_code,5,0.8
5,PACKAGEDRAWINGS,2,1,NaN,NaN,5,0.8
6,PROCESSFLOWDIAGRAM,2.1,2,P1-REF-2012-123-014,doc_code,5,0.8
7,P&IDREFRIGERATIONUNIT,2.2,2,P1-REF-2012-123-001,doc_code,5,0.8
8,GENERALARRANGEMENTDRAWING,2.3,2,P1-REF-2012-123-003,doc_code,5,0.8
9,FOUNDATIONLAYOUT,2.4,2,P1-REF-2012-123-012,doc_code,5,0.8
10,P.V.&H.E.,3,1,NaN,NaN,5,0.8
11,AIRCOOLERCONDENSERDATASHEET,3.1,2,P1-REF-DSS-12-123-011,doc_code,5,0.8
12,AIRCOOLERCONDENSERGENERALARRANGEMENT,3.2,2,P1-REF-2012-123-005,doc_code,5,0.8
13,AIRCOOLERCONDENSERTUBEBUNDLEDRAWING,3.3,2,P1-REF-2012-123-016,doc_code,5,0.8
14,AIRCOOLERCONDENSERSTRUCTURALPARTLIST&AS...,3.4,2,P1-REF-2012-123-034,doc_code,5,0.8
15,AIRCOOLERCONDENSERTUBEBUNDLEFRAMEDRAWING,3.5,2,P1-REF-2012-123-035,doc_code,5,0.8
16,AIRCONDENSERTESTINGPROCEDURE,3.6,2,P1-REF-PRD-12-123-001,doc_code,5,0.8
17,ECONOMIZERDATASHEET,3.7,2,P1-REF-DSS-12-123-012,doc_code,5,0.8
18,ECONOMIZERASSEMBLYDRAWING,3.8,2,P1-REF-2012-123-006,doc_code,5,0.8
19,KODRUMDATASHEET,3.9,2,P1-REF-DSS-12-123-013,doc_code,5,0.8
20,KODRUMASSEMBLYDRAWING,3.10,2,P1-REF-2012-123-007,doc_code,5,0.8
21,OILCOOLERDATASHEET,3.11,2,P1-REF-DSS-12-123-014,doc_code,5,0.8
22,OILCOOLERASSEMBLYDRAWING,3.12,2,P1-REF-2012-123-008,doc_code,5,0.8
23,RECEIVERDATASHEET,3.13,2,P1-REF-DSS-12-123-017,doc_code,5,0.8
24,RECEIVERASSEMBLYDRAWING,3.14,2,P1-REF-2012-123-010,doc_code,5,0.8
25,OILSEPARATORDATASHEET,3.15,2,P1-REF-DSS-12-123-016,doc_code,5,0.8
26,OILSEPARATORASSEMBLYDRAWING,3.16,2,P1-REF-2012-123-009,doc_code,5,0.8
27,SUCTIONFILTERDATASHEET,3.17,2,P1-REF-DSS-12-123-018,doc_code,5,0.8
28,SUCTIONFILTERASSEMBLYDRAWING,3.18,2,P1-REF-2012-123-011,doc_code,5,0.8
29,OILFILTERDATASHEET,3.19,2,P1-REF-DSS-12-123-015,doc_code,5,0.8
30,OILFILTERASSEMBLYDRAWING,3.20,2,P1-REF-2012-123-019,doc_code,5,0.8
31,P.V.&H.E.TESTINGPROCEDURES,3.21,2,P1-REF-PRD-12-123-013,doc_code,5,0.8
32,COMPRESSOR&PUMPS,4,1,NaN,NaN,5,0.8
33,COMPRESSORDRAWINGS(OUTLINE&SECTIONAL),4.1,2,P1-REF-2012-123-020,doc_code,5,0.8
34,COMPRESSORMECHANICALSEALDRAWING,4.2,2,P1-REF-DSS-12-123-007,doc_code,5,0.8
35,COMPRESSORTESTINGPROCEDURE,4.3,2,P1-REF-PRD-12-123-002,doc_code,5,0.8
36,COMPRESSORPERFORMANCECURVE,4.4,2,P1-REF-DSS-12-123-023,doc_code,5,0.8
37,COMPRESSORSTARTINGTORQUECURVE,4.5,2,P1-REF-DSS-12-123-004,doc_code,5,0.8
38,TRAINTORSIONALANALYSIS,4.6,2,P1-REF-RCA-12-123-010,doc_code,5,0.8
39,COMPRESSORDATASHEETS,4.7,2,P1-REF-DSS-12-123-003,doc_code,5,0.8
40,COMPRESSORCOUPLINGDRAWING,4.8,2,P1-REF-2012-123-022,doc_code,5,0.8
41,OILPUMPDRAWING,4.9,2,P1-REF-2012-123-027,doc_code,5,0.8
42,OILPUMPDATASHEET,4.10,2,P1-REF-DSS-12-123-021,doc_code,5,0.8
43,ELECTRICAL,5,1,NaN,NaN,5,0.8
44,ELECTRICAL&UTILITIESCONSUMPTIONLIST,5.1,2,P1-REF-LST-12-123-003,doc_code,5,0.8
45,MAINMOTORDRAWING,5.2,2,P1-REF-2012-123-027,doc_code,5,0.8
46,MAINMOTORDATASHEETS,5.3,2,P1-REF-DSS-12-123-005,doc_code,5,0.8
47,MAINMOTORTERMINALBOXES,5.4,2,P1-REF-2012-123-030,doc_code,6,0.8
48,MAINMOTORTESTINGPROCEDURE,5.5,2,P1-REF-PRD-12-123-006,doc_code,6,0.8
49,FANMOTORSDRAWING,5.6,2,P1-REF-2012-123-024,doc_code,6,0.8
50,FANMOTORSDATASHEET&CURVES,5.7,2,P1-REF-DSS-12-123-019,doc_code,6,0.8
51,PUMPMOTORSDRAWING,5.8,2,P1-REF-2012-123-025,doc_code,6,0.8
52,PUMPMOTORSDATASHEET&CURVES,5.9,2,P1-REF-DSS-12-123-020,doc_code,6,0.8
53,PIPING,6,1,NaN,NaN,6,0.8
54,LINELIST,6.1,2,P1-REF-LST-12-123-008,doc_code,6,0.8
55,PIPINGTESTINGPROCEDURE,6.2,2,P1-REF-PRD-12-123-014,doc_code,6,0.8
56,PIPINGCLASS,6.3,2,P1-REF-SPC-12-123-001,doc_code,6,0.8
57,INSTRUMENTATION&CONTROL,7,1,NaN,NaN,6,0.8
58,CONTROLSYSTEMBLOCKDIAGRAM,7.1,2,P1-REF-2012-123-017,doc_code,6,0.8
59,INSTRUMENTLIST&SETTING,7.2,2,P1-REF-LST-12-123-005,doc_code,6,0.8
60,INSTRUMENTDATASHEETS,7.3,2,P1-REF-DSS-12-123-002,doc_code,6,0.8
61,INSTRUMENTHOOKUP,7.4,2,P1-REF-2012-123-028,doc_code,6,0.8
62,ELECTRICALHOOKUP,7.5,2,P1-REF-2012-123-031,doc_code,6,0.8
63,SAFETYVALVESCALCULATIONSHEETS,7.6,2,P1-REF-RCA-12-123-003,doc_code,6,0.8
64,CAUSE&EFFECTSCHART,7.7,2,P1-REF-LST-12-123-011,doc_code,6,0.8
65,PACKAGEI/OLIST,7.8,2,P1-REF-LST-12-123-006,doc_code,6,0.8
66,CABLESLIST,7.9,2,P1-REF-LST-12-123-004,doc_code,6,0.8
67,LOCALGAUGEBOARD&JBLAYOUT,7.10,2,P1-REF-2012-123-018,doc_code,6,0.8
68,INSTRUMENTSANDCABLETRAYLAYOUT,7.11,2,P1-REF-2012-123-004,doc_code,6,0.8
69,cYa2mtaeeelow,NaN,1,P1-21-1-0003,doc_code,5,0.8
70,cYanataGnGentYo,NaN,1,P1-REF-DSS-12-12-08,doc_code,5,0.8
71,cYamantYel,NaN,1,P1-ReF-SpPc-12-123-002,doc_code,5,0.8
72,Yamante,NaN,1,P1-REF-SP-12-123-033,doc_code,5,0.8
73,cYa2maGaYntYalo,NaN,1,P1-Ge3-014,doc_code,5,0.8
74,ca2nmaenaaY,NaN,1,P1-REF-2012-123-001,doc_code,5,0.8
75,2.3GN,NaN,1,P1-Ref-2012-123-003,doc_code,5,0.8
76,2 4ao,NaN,1,P1-Ref-2012-123-012,doc_code,5,0.8
77,31a,NaN,1,P1-Ref-DSs-12-123-011,doc_code,5,0.8
78,a4eYY,NaN,1,0,page,5,0.8
79,ataette,NaN,1,P1-REF-PRD-12-123-001,doc_code,5,0.8
80,Yamaa,NaN,1,P1-REf-DSS-12-123-012,doc_code,5,0.8
81,atntate,NaN,1,P1-e-012-123-006,doc_code,5,0.8
82,Yaan1tGntaYY,NaN,1,P1-E-D0-12-13-013,doc_code,5,0.8
83,3.14ae,NaN,1,1,page,5,0.8
84,cYamaaGentaYYYlo,NaN,1,P1-0112-010,doc_code,5,0.8
85,c3.21 PaGn aYeo,NaN,1,P1-REF-PRD-12-123-013,doc_code,5,0.8
86,4RL,NaN,1,P1-REF-201-123-020502,doc_code,5,0.8
87,canmanGenanaYeeow,NaN,1,P1-REF-PRD-12-1202,doc_code,5,0.8
88,canmaeeelo,NaN,1,P1-ReF-DSS-12-123-023,doc_code,5,0.8
89,amaet,NaN,1,P1-Re-e11-010,doc_code,5,0.8
90,cYanmaaYtYlowb,NaN,1,P1-Re-DSS-12-123-003,doc_code,5,0.8
91,cYanamaaeaYetYlo,NaN,1,1-1e-021,doc_code,5,0.8
92,cYanaten,NaN,1,P1-REF-DSS-12-123-021,doc_code,5,0.8
93,1e,NaN,1,P1-REF-LST-12-123-003,doc_code,5,0.8
94,m1OP,NaN,1,P1-REF-LST-12-12-03,doc_code,5,0.8
95,MaINO,NaN,1,P1-REF-2012-123-030,doc_code,6,0.8
96,t,NaN,1,P1-REF-PRD-12-123-006,doc_code,6,0.8
97,caGemte,NaN,1,P1-REf-2012-123-024,doc_code,6,0.8
98,7.maGaGnmaeYYY,57,1,P1-REF-DSS-12-123-019,doc_code,6,0.8
99,.8,NaN,1,cP1-REF-2012-123-025,doc_code,6,0.8

## 5. Passer chaque contenu de Table of Contents au LLM #1

Une région de TOC = un appel à `classify_sections()` (même prompt, même
schéma `SectionClassificationResult` que la production,
`src/llm/classifier.py` inchangé). Chaque entrée organisée de la région
devient un "section candidate" avec son titre, son numéro de section et
sa page imprimée -- c'est le contenu réel du sommaire, pas un extrait du
corps du document.

In [25]:
from src.llm.config import ENABLE_LLM, LLM_MODEL
import importlib
import src.llm.classifier
importlib.reload(src.llm.classifier)
importlib.reload(src.llm.prompts)
importlib.reload(src.llm.schemas)
from src.llm.classifier import classify_sections

def region_entries_to_payload(region_index: int, entries) -> list[dict]:
    payload = []
    for j, entry in enumerate(entries):
        payload.append({
            "section_id": f"toc{region_index}_e{j}",
            "title": entry.text,
            "section_number": entry.section_number,
            "page_start": entry.printed_page_ref,
            "page_end": entry.printed_page_ref,
            "level": entry.level,
            "confidence": round(entry.confidence, 3),
            "text": "",  
        })
    return payload


results_by_region = []

for i, entries in enumerate(organized_regions, 1):
    payload = region_entries_to_payload(i, entries)
    print(f"\n=== TOC region {i} --  {len(payload)} sections candidates ===")

    if not ENABLE_LLM:
        print("OPENAI_API_KEY absente -> appel non effectue. Payload pret :")
        print(json_lib.dumps(payload[:5], ensure_ascii=False, indent=2), "..." if len(payload) > 5 else "")
        results_by_region.append(None)
        continue

    try:
        result = classify_sections(payload)
    except Exception as exc:
        print(f"LLM #1 a echoue pour la region {i} : {exc}")
        results_by_region.append(None)
        continue

    print("Sections retenues :", result.selected_sections)
    display(pd.DataFrame([c.model_dump() for c in result.sections]))
    results_by_region.append(result)

=== TOC region 1 --  118 sections candidates ===
Sections retenues : ['toc1_e11', 'toc1_e12', 'toc1_e17', 'toc1_e19', 'toc1_e21', 'toc1_e23', 'toc1_e25', 'toc1_e27', 'toc1_e29', 'toc1_e39', 'toc1_e42', 'toc1_e46', 'toc1_e50', 'toc1_e52', 'toc1_e60', 'toc1_e100']

,section_id,relevance_score,reason,potential_information
0,toc1_e0,10,The title suggests a list of documents and dra...,[]
1,toc1_e1,10,A subvendor list is unlikely to provide direct...,[]
2,toc1_e2,20,Noise data sheets may contain some operational...,[]
3,toc1_e3,10,A lubricant list is unlikely to contain specif...,[]
4,toc1_e4,20,Painting specifications may include some detai...,[]
5,toc1_e5,20,Package drawings may provide some context but ...,[]
6,toc1_e6,20,Process flow diagrams may provide context for ...,[]
7,toc1_e7,30,P&ID drawings may include some equipment ident...,[]
8,toc1_e8,30,General arrangement drawings may provide some ...,[]
9,toc1_e9,30,Foundation layout may provide context for equi...,[]
10,toc1_e10,10,The title does not suggest any specific equipm...,[]
11,toc1_e11,80,Data sheets for air cooler condensers typicall...,"[Manufacturer / Brand, Equipment name or type,..."
12,toc1_e12,60,General arrangement drawings for air cooler co...,"[Dimensions, Weight, Technical specifications]"
13,toc1_e13,30,Tube bundle drawings may provide some context ...,[]
14,toc1_e14,40,Structural part lists may contain some assembl...,[]
15,toc1_e15,30,Frame drawings may provide context but are not...,[]
16,toc1_e16,20,Testing procedures may include some operationa...,[]
17,toc1_e17,80,Data sheets for economizers typically contain ...,"[Manufacturer / Brand, Equipment name or type,..."
18,toc1_e18,60,Assembly drawings for economizers may include ...,"[Dimensions, Weight, Technical specifications]"
19,toc1_e19,80,Data sheets for KO drums typically contain det...,"[Manufacturer / Brand, Equipment name or type,..."
20,toc1_e20,30,Assembly drawings for KO drums may provide con...,[]
21,toc1_e21,80,Data sheets for oil coolers typically contain ...,"[Manufacturer / Brand, Equipment name or type,..."
22,toc1_e22,60,Assembly drawings for oil coolers may include ...,"[Dimensions, Weight, Technical specifications]"
23,toc1_e23,80,Data sheets for receivers typically contain de...,"[Manufacturer / Brand, Equipment name or type,..."
24,toc1_e24,60,Assembly drawings for receivers may include so...,"[Dimensions, Weight, Technical specifications]"
25,toc1_e25,80,Data sheets for oil separators typically conta...,"[Manufacturer / Brand, Equipment name or type,..."
26,toc1_e26,60,Assembly drawings for oil separators may inclu...,"[Dimensions, Weight, Technical specifications]"
27,toc1_e27,80,Data sheets for suction filters typically cont...,"[Manufacturer / Brand, Equipment name or type,..."
28,toc1_e28,60,Assembly drawings for suction filters may incl...,"[Dimensions, Weight, Technical specifications]"
29,toc1_e29,80,Data sheets for oil filters typically contain ...,"[Manufacturer / Brand, Equipment name or type,..."
30,toc1_e30,60,Assembly drawings for oil filters may include ...,"[Dimensions, Weight, Technical specifications]"
31,toc1_e31,20,Testing procedures for compressors may include...,[]
32,toc1_e32,10,The title does not suggest any specific equipm...,[]
33,toc1_e33,60,Drawings for compressors may include some spec...,"[Dimensions, Weight, Technical specifications]"
34,toc1_e34,60,Mechanical seal drawings may include some spec...,"[Dimensions, Weight, Technical specifications]"
35,toc1_e35,20,Testing procedures for compressors may include...,[]
36,toc1_e36,20,Performance curves may provide some operationa...,[]
37,toc1_e37,20,Starting torque curves may provide some operat...,[]
38,toc1_e38,20,Torsional analysis may provide some operationa...,[]
39,toc1_e39,80,Data sheets for compressors typically contain ...,"[Manufacturer / Brand, Equipment name or type,..."
40,toc1_e40,60,Coupling drawings may include some specificati...,"[Dimensions, Weight, Technical specifications]"
41,toc1_e41,60,Oil pump drawings may include some specificati...,"[Dimensions, Weight, Technical specifications]"
42,toc1_e42,80,Data sheets for oil pumps typically contain de...,"[Manufacturer / Brand, Equipment name or type,..."
43,toc1_e43,10,The title does not suggest any specific equipm...,[]
44,toc1_e44,20,Utilities consumption lists may provide some o...,[]
45,toc1_e45,60,Main motor drawings may include some specifica...,"[Dimensions, Weight, Technical specifications]"
46,toc1_e46,80,Data sheets for main motors typically contain ...,"[Manufacturer / Brand, Equipment name or type,..."
47,toc1_e47,60,Terminal box drawings may include some specifi...,"[Dimensions, Weight, Technical specifications]"
48,toc1_e48,20,Testing procedures for main motors may include...,[]
49,toc1_e49,60,Fan motor drawings may include some specificat...,"[Dimensions, Weight, Technical specifications]"
50,toc1_e50,80,Data sheets for fan motors typically contain d...,"[Manufacturer / Brand, Equipment name or type,..."
51,toc1_e51,60,Pump motor drawings may include some specifica...,"[Dimensions, Weight, Technical specifications]"
52,toc1_e52,80,Data sheets for pump motors typically contain ...,"[Manufacturer / Brand, Equipment name or type,..."
53,toc1_e53,10,The title does not suggest any specific equipm...,[]
54,toc1_e54,20,Line lists may provide some operational parame...,[]
55,toc1_e55,20,Testing procedures for piping may include some...,[]
56,toc1_e56,20,Piping class specifications may provide some c...,[]
57,toc1_e57,10,The title does not suggest any specific equipm...,[]
58,toc1_e58,20,Control system block diagrams may provide some...,[]
59,toc1_e59,30,Instrument lists may include some identificati...,[]
60,toc1_e60,80,Data sheets for instruments typically contain ...,"[Manufacturer / Brand, Equipment name or type,..."
61,toc1_e61,20,Hook-up instructions may provide some context ...,[]
62,toc1_e62,20,Electrical hook-up instructions may provide so...,[]
63,toc1_e63,20,Safety valve calculation sheets may provide so...,[]
64,toc1_e64,10,Cause and effects charts are unlikely to conta...,[]
65,toc1_e65,20,I/O lists may provide some operational paramet...,[]
66,toc1_e66,20,Cable lists may provide some operational param...,[]
67,toc1_e67,20,Gauge board layouts may provide some context b...,[]
68,toc1_e68,20,Instrument and cable tray layouts may provide ...,[]
69,toc1_e69,10,The title does not suggest any specific equipm...,[]
70,toc1_e70,10,The title does not suggest any specific equipm...,[]
71,toc1_e71,10,The title does not suggest any specific equipm...,[]
72,toc1_e72,10,The title does not suggest any specific equipm...,[]
73,toc1_e73,10,The title does not suggest any specific equipm...,[]
74,toc1_e74,10,The title does not suggest any specific equipm...,[]
75,toc1_e75,10,The title does not suggest any specific equipm...,[]
76,toc1_e76,10,The title does not suggest any specific equipm...,[]
77,toc1_e77,10,The title does not suggest any specific equipm...,[]
78,toc1_e78,10,The title does not suggest any specific equipm...,[]
79,toc1_e79,10,The title does not suggest any specific equipm...,[]
80,toc1_e80,10,The title does not suggest any specific equipm...,[]
81,toc1_e81,10,The title does not suggest any specific equipm...,[]
82,toc1_e82,10,The title does not suggest any specific equipm...,[]
83,toc1_e83,10,The title does not suggest any specific equipm...,[]
84,toc1_e84,10,The title does not suggest any specific equipm...,[]
85,toc1_e85,10,The title does not suggest any specific equipm...,[]
86,toc1_e86,10,The title does not suggest any specific equipm...,[]
87,toc1_e87,10,The title does not suggest any specific equipm...,[]
88,toc1_e88,10,The title does not suggest any specific equipm...,[]
89,toc1_e89,10,The title does not suggest any specific equipm...,[]
90,toc1_e90,10,The title does not suggest any specific equipm...,[]
91,toc1_e91,10,The title does not suggest any specific equipm...,[]
92,toc1_e92,10,The title does not suggest any specific equipm...,[]
93,toc1_e93,10,The title does not suggest any specific equipm...,[]
94,toc1_e94,10,The title does not suggest any specific equipm...,[]
95,toc1_e95,10,The title does not suggest any specific equipm...,[]
96,toc1_e96,10,The title does not suggest any specific equipm...,[]
97,toc1_e97,10,The title does not suggest any specific equipm...,[]
98,toc1_e98,10,The title does not suggest any specific equipm...,[]
99,toc1_e99,10,The title does not suggest any specific equipm...,[]
100,toc1_e100,80,Data sheets for pump motors typically contain ...,"[Manufacturer / Brand, Equipment name or type,..."
101,toc1_e101,10,The title does not suggest any specific equipm...,[]
102,toc1_e102,10,The title does not suggest any specific equipm...,[]
103,toc1_e103,10,The title does not suggest any specific equipm...,[]
104,toc1_e104,10,The title does not suggest any specific equipm...,[]
105,toc1_e105,10,The title does not suggest any specific equipm...,[]
106,toc1_e106,10,The title does not suggest any specific equipm...,[]
107,toc1_e107,10,The title does not suggest any specific equipm...,[]
108,toc1_e108,10,The title does not suggest any specific equipm...,[]
109,toc1_e109,10,The title does not suggest any specific equipm...,[]
110,toc1_e110,10,The title does not suggest any specific equipm...,[]
111,toc1_e111,10,The title does not suggest any specific equipm...,[]
112,toc1_e112,10,The title does not suggest any specific equipm...,[]
113,toc1_e113,10,The title does not suggest any specific equipm...,[]
114,toc1_e114,10,The title does not suggest any specific equipm...,[]
115,toc1_e115,10,The title does not suggest any specific equipm...,[]
116,toc1_e116,20,Gauge board layouts may provide some context b...,[]
117,toc1_e117,10,The title does not suggest any specific equipm...,[]

=== TOC region 2 --  58 sections candidates ===
Sections retenues : ['toc2_e20', 'toc2_e21', 'toc2_e22', 'toc2_e23', 'toc2_e24', 'toc2_e25', 'toc2_e26', 'toc2_e27', 'toc2_e28', 'toc2_e29', 'toc2_e30', 'toc2_e31', 'toc2_e32', 'toc2_e49', 'toc2_e50', 'toc2_e54']

,section_id,relevance_score,reason,potential_information
0,toc2_e0,5,Safety instructions typically do not contain s...,[]
1,toc2_e1,10,Transport and packing sections usually focus o...,[]
2,toc2_e2,15,A packing list may include some identification...,[]
3,toc2_e3,15,Packing drawings may provide some context but ...,[]
4,toc2_e4,30,Installation instructions may contain some spe...,[]
5,toc2_e5,25,Lifting drawings may include dimensions but ar...,[]
6,toc2_e6,20,Preservation and storage procedures are unlike...,[]
7,toc2_e7,25,Skid positioning and leveling procedures may i...,[]
8,toc2_e8,20,Commissioning and startup sections are general...,[]
9,toc2_e9,25,Commissioning procedures may include some oper...,[]
10,toc2_e10,30,Motor alignment procedures may touch on specif...,[]
11,toc2_e11,10,Vacuum test procedures are unlikely to contain...,[]
12,toc2_e12,15,Operation sections may provide some operationa...,[]
13,toc2_e13,10,Operating instructions are typically procedura...,[]
14,toc2_e14,20,Control philosophy may include some operationa...,[]
15,toc2_e15,30,Maintenance manuals may contain some specifica...,[]
16,toc2_e16,10,General maintenance instructions are unlikely ...,[]
17,toc2_e17,10,Periodic inspection and adjustment instruction...,[]
18,toc2_e18,5,Maintenance schedules typically do not include...,[]
19,toc2_e19,10,Troubleshooting sections are generally procedu...,[]
20,toc2_e20,70,Operating and instruction manuals for compress...,"[Manufacturer / Brand, Equipment name or type,..."
21,toc2_e21,70,Operating and instruction manuals for pumps li...,"[Manufacturer / Brand, Equipment name or type,..."
22,toc2_e22,70,Operating and instruction manuals for main mot...,"[Manufacturer / Brand, Equipment name or type,..."
23,toc2_e23,70,Operating and instruction manuals for pump mot...,"[Manufacturer / Brand, Equipment name or type,..."
24,toc2_e24,70,Operating and instruction manuals for compress...,"[Manufacturer / Brand, Equipment name or type,..."
25,toc2_e25,70,Operating and instruction manuals for air cool...,"[Manufacturer / Brand, Equipment name or type,..."
26,toc2_e26,70,Operating and instruction manuals for economiz...,"[Manufacturer / Brand, Equipment name or type,..."
27,toc2_e27,70,Operating and instruction manuals for KO drums...,"[Manufacturer / Brand, Equipment name or type,..."
28,toc2_e28,70,Operating and instruction manuals for oil cool...,"[Manufacturer / Brand, Equipment name or type,..."
29,toc2_e29,70,Operating and instruction manuals for receiver...,"[Manufacturer / Brand, Equipment name or type,..."
30,toc2_e30,70,Operating and instruction manuals for oil sepa...,"[Manufacturer / Brand, Equipment name or type,..."
31,toc2_e31,70,Operating and instruction manuals for suction ...,"[Manufacturer / Brand, Equipment name or type,..."
32,toc2_e32,70,Operating and instruction manuals for oil filt...,"[Manufacturer / Brand, Equipment name or type,..."
33,toc2_e33,20,Special tools lists may include some equipment...,[]
34,toc2_e34,15,Spare parts lists may include some identificat...,[]
35,toc2_e35,10,Spare part lists for commissioning are unlikel...,[]
36,toc2_e36,0,This section title does not provide any contex...,[]
37,toc2_e37,0,This section title does not provide any contex...,[]
38,toc2_e38,0,This section title does not provide any contex...,[]
39,toc2_e39,0,This section title does not provide any contex...,[]
40,toc2_e40,0,This section title does not provide any contex...,[]
41,toc2_e41,0,This section title does not provide any contex...,[]
42,toc2_e42,0,This section title does not provide any contex...,[]
43,toc2_e43,0,This section title does not provide any contex...,[]
44,toc2_e44,0,This section title does not provide any contex...,[]
45,toc2_e45,0,This section title does not provide any contex...,[]
46,toc2_e46,0,This section title does not provide any contex...,[]
47,toc2_e47,0,This section title does not provide any contex...,[]
48,toc2_e48,0,This section title does not provide any contex...,[]
49,toc2_e49,70,Operating and instruction manuals for main mot...,"[Manufacturer / Brand, Equipment name or type,..."
50,toc2_e50,70,Operating and instruction manuals for pump mot...,"[Manufacturer / Brand, Equipment name or type,..."
51,toc2_e51,0,This section title does not provide any contex...,[]
52,toc2_e52,0,This section title does not provide any contex...,[]
53,toc2_e53,0,This section title does not provide any contex...,[]
54,toc2_e54,70,Operating and instruction manuals for receiver...,"[Manufacturer / Brand, Equipment name or type,..."
55,toc2_e55,0,This section title does not provide any contex...,[]
56,toc2_e56,0,This section title does not provide any contex...,[]
57,toc2_e57,0,This section title does not provide any contex...,[]

=== TOC region 3 --  77 sections candidates ===
Sections retenues : ['toc3_e14', 'toc3_e16', 'toc3_e17', 'toc3_e71']

,section_id,relevance_score,reason,potential_information
0,toc3_e0,5,The introduction typically provides a general ...,[]
1,toc3_e1,20,The general description of the compressor may ...,[]
2,toc3_e2,30,The mechanism description may touch on technic...,[]
3,toc3_e3,25,The aspiration phase may include some operatio...,[]
4,toc3_e4,25,The compression phase may discuss operational ...,[]
5,toc3_e5,25,The discharge phase may include operational pa...,[]
6,toc3_e6,20,The definition of the volumetric ratio may be ...,[]
7,toc3_e7,20,Reasons for adjusting the volumetric ratio may...,[]
8,toc3_e8,20,The variable mechanism may discuss functionali...,[]
9,toc3_e9,20,External adjustment may relate to operational ...,[]
10,toc3_e10,15,Precautions during adjustments are unlikely to...,[]
11,toc3_e11,30,Mechanisms of other components may provide som...,[]
12,toc3_e12,25,Oil flow may discuss operational parameters bu...,[]
13,toc3_e13,40,An exploded view may provide some visual ident...,[]
14,toc3_e14,50,A parts list is likely to contain specific par...,"[Part number, Equipment identification number]"
15,toc3_e15,30,A longitudinal view may provide some context b...,[]
16,toc3_e16,60,External dimensions are likely to provide rele...,"[Dimensions, Weight]"
17,toc3_e17,70,A table of dimensions is likely to contain spe...,"[Dimensions, Weight]"
18,toc3_e18,20,Dismantling may discuss procedures but lacks s...,[]
19,toc3_e19,15,Preparation for dismantling is unlikely to con...,[]
20,toc3_e20,10,Tooling may discuss necessary tools but lacks ...,[]
21,toc3_e21,15,Removing the compressor may discuss procedures...,[]
22,toc3_e22,10,Refrigerant recovery is unlikely to contain sp...,[]
23,toc3_e23,10,Dismantling auxiliary equipment may discuss pr...,[]
24,toc3_e24,10,Lifting and removing the compressor may discus...,[]
25,toc3_e25,10,Dismantling sequence may discuss procedures bu...,[]
26,toc3_e26,10,Mechanical seals may discuss components but la...,[]
27,toc3_e27,10,Dismantling may discuss procedures but lacks s...,[]
28,toc3_e28,10,Inspection is unlikely to contain specific equ...,[]
29,toc3_e29,10,Capacity indicators may discuss functionality ...,[]
30,toc3_e30,10,Removing the capacity sensor may discuss proce...,[]
31,toc3_e31,5,This section is too vague to provide any usefu...,[]
32,toc3_e32,10,Dismantling the cover may discuss procedures b...,[]
33,toc3_e33,10,Dismantling may discuss procedures but lacks s...,[]
34,toc3_e34,10,Inspection is unlikely to contain specific equ...,[]
35,toc3_e35,10,Dismantling may discuss procedures but lacks s...,[]
36,toc3_e36,10,Dismantling may discuss procedures but lacks s...,[]
37,toc3_e37,10,Inspection is unlikely to contain specific equ...,[]
38,toc3_e38,10,Dismantling may discuss procedures but lacks s...,[]
39,toc3_e39,10,Dismantling may discuss procedures but lacks s...,[]
40,toc3_e40,10,Dismantling may discuss procedures but lacks s...,[]
41,toc3_e41,10,Inspection is unlikely to contain specific equ...,[]
42,toc3_e42,10,Dismantling may discuss procedures but lacks s...,[]
43,toc3_e43,10,Dismantling may discuss procedures but lacks s...,[]
44,toc3_e44,10,Inspection is unlikely to contain specific equ...,[]
45,toc3_e45,10,Dismantling may discuss procedures but lacks s...,[]
46,toc3_e46,10,Dismantling may discuss procedures but lacks s...,[]
47,toc3_e47,10,Inspection is unlikely to contain specific equ...,[]
48,toc3_e48,10,Dismantling may discuss procedures but lacks s...,[]
49,toc3_e49,10,Dismantling may discuss procedures but lacks s...,[]
50,toc3_e50,10,Inspection is unlikely to contain specific equ...,[]
51,toc3_e51,10,Dismantling may discuss procedures but lacks s...,[]
52,toc3_e52,10,Dismantling may discuss procedures but lacks s...,[]
53,toc3_e53,10,Inspection is unlikely to contain specific equ...,[]
54,toc3_e54,10,Dismantling may discuss procedures but lacks s...,[]
55,toc3_e55,5,This section is too vague to provide any usefu...,[]
56,toc3_e56,20,Remounting may discuss procedures but lacks sp...,[]
57,toc3_e57,10,The housing and bearings may discuss component...,[]
58,toc3_e58,10,The rotor housing may discuss components but l...,[]
59,toc3_e59,10,The suction cover may discuss components but l...,[]
60,toc3_e60,10,The thrust bearing may discuss components but ...,[]
61,toc3_e61,10,The bearing cover may discuss components but l...,[]
62,toc3_e62,10,The cover may discuss components but lacks spe...,[]
63,toc3_e63,10,The unloading cover may discuss components but...,[]
64,toc3_e64,10,The mechanical seal may discuss components but...,[]
65,toc3_e65,20,Dismantling and adjusting the capacity indicat...,[]
66,toc3_e66,5,This section is too vague to provide any usefu...,[]
67,toc3_e67,20,Dismantling and adjusting the capacity indicat...,[]
68,toc3_e68,5,This section is too vague to provide any usefu...,[]
69,toc3_e69,20,Inspection may discuss operational parameters ...,[]
70,toc3_e70,20,Assembly and adjustment may discuss operationa...,[]
71,toc3_e71,30,Standard dimensions of components may provide ...,[Dimensions]
72,toc3_e72,5,This section is too vague to provide any usefu...,[]
73,toc3_e73,5,This section is too vague to provide any usefu...,[]
74,toc3_e74,5,This section is too vague to provide any usefu...,[]
75,toc3_e75,5,This section is too vague to provide any usefu...,[]
76,toc3_e76,5,This section is too vague to provide any usefu...,[]

=== TOC region 4 --  12 sections candidates ===
Sections retenues : ['toc4_e1', 'toc4_e2', 'toc4_e4', 'toc4_e5', 'toc4_e6', 'toc4_e7']

,section_id,relevance_score,reason,potential_information
0,toc4_e0,60,The title suggests it may contain information ...,"[Manufacturer / Brand, Equipment name or type]"
1,toc4_e1,85,The title 'FAN DATA SHEET' indicates it likely...,"[Model / Type / Reference, Technical specifica..."
2,toc4_e2,70,The title suggests it may contain operational ...,"[Technical specifications, Operating parameter..."
3,toc4_e3,30,The title is vague and does not suggest specif...,[]
4,toc4_e4,60,The title indicates it may contain specificati...,"[Technical specifications, Dimensions, Weight]"
5,toc4_e5,50,The title suggests it may contain process data...,"[Operating parameters, Technical specifications]"
6,toc4_e6,60,"Similar to section 0, the title suggests it ma...","[Manufacturer / Brand, Equipment name or type]"
7,toc4_e7,85,The title 'Fa Da Se' likely refers to fan data...,"[Model / Type / Reference, Technical specifica..."
8,toc4_e8,20,The title is unclear and does not suggest any ...,[]
9,toc4_e9,10,The title is vague and does not suggest any sp...,[]
10,toc4_e10,10,The title is vague and does not suggest any sp...,[]
11,toc4_e11,0,The title does not provide any context or info...,[]

=== TOC region 5 --  31 sections candidates ===
Sections retenues : []

,section_id,relevance_score,reason,potential_information
0,toc5_e0,10,The introduction typically provides a general ...,[]
1,toc5_e1,30,General installation and operation instruction...,[]
2,toc5_e2,20,Storage instructions are unlikely to contain s...,[]
3,toc5_e3,20,Characteristics for storage areas may not incl...,[]
4,toc5_e4,20,This section is focused on storage procedures ...,[]
5,toc5_e5,20,Inspection procedures may touch on equipment b...,[]
6,toc5_e6,20,This section discusses storage during pre-comm...,[]
7,toc5_e7,20,Storage during equipment downtime is unlikely ...,[]
8,toc5_e8,20,This section discusses components for reassemb...,[]
9,toc5_e9,30,Transport and lifting instructions may contain...,[]
10,toc5_e10,40,This section may list special tools and equipm...,[]
11,toc5_e11,40,Assembly procedures may include some specifica...,[]
12,toc5_e12,40,Connections may include some relevant specific...,[]
13,toc5_e13,40,Pre-commissioning procedures may touch on equi...,[]
14,toc5_e14,40,Commissioning procedures may include some rele...,[]
15,toc5_e15,40,Start-up and shutdown procedures may include s...,[]
16,toc5_e16,20,Periodic checks are unlikely to provide specif...,[]
17,toc5_e17,20,Functionality and integrity checks are unlikel...,[]
18,toc5_e18,20,Lubrication instructions are unlikely to provi...,[]
19,toc5_e19,30,Maintenance instructions may contain some rele...,[]
20,toc5_e20,30,General maintenance instructions may contain s...,[]
21,toc5_e21,20,Cleaning instructions are unlikely to provide ...,[]
22,toc5_e22,20,Internal inspection instructions are unlikely ...,[]
23,toc5_e23,20,Internal cleaning instructions are unlikely to...,[]
24,toc5_e24,20,Problem resolution instructions are unlikely t...,[]
25,toc5_e25,20,Leakage issues are unlikely to provide specifi...,[]
26,toc5_e26,20,Leakage issues are unlikely to provide specifi...,[]
27,toc5_e27,20,Leakage issues are unlikely to provide specifi...,[]
28,toc5_e28,20,Leakage issues are unlikely to provide specifi...,[]
29,toc5_e29,20,Damage repair instructions are unlikely to pro...,[]
30,toc5_e30,20,Hydraulic testing instructions are unlikely to...,[]

## 6. Vue d'ensemble : sections retenues, toutes régions confondues

In [29]:
rows = []
for i, (entries, result) in enumerate(zip(organized_regions, results_by_region), 1):
    if result is None:
        continue
    selected_ids = set(result.selected_sections)
    for j, entry in enumerate(entries):
        section_id = f"toc{i}_e{j}"
        rows.append({
            "toc_region": i,
            "section_id": section_id,
            "title": entry.text,
            "page": entry.printed_page_ref,
            "retenue": section_id in selected_ids,
        })

if rows:
    overview = pd.DataFrame(rows)
    display(overview.head(10))
    print("Total retenues :", int(overview["retenue"].sum()), "/", len(overview))
else:
    print("Aucun resultat LLM disponible (verifiez OPENAI_API_KEY dans .env).")

,toc_region,section_id,title,page,retenue
0,1,toc1_e0,DOCUMENTS&DRAWINGSLIST,P1-REF-LST-12-123-007,False
1,1,toc1_e1,SUBVENDORLIST,P1-REF-LST-12-123-003,False
2,1,toc1_e2,NOISEDATASHEET,P1-REF-DSS-12-123-008,False
3,1,toc1_e3,LUBRICANTLIST,P1-REF-SPC-12-123-002,False
4,1,toc1_e4,PAINTINGSPECIFICATIONS,P1-REF-SPC-12-123-003,False
5,1,toc1_e5,PACKAGEDRAWINGS,NaN,False
6,1,toc1_e6,PROCESSFLOWDIAGRAM,P1-REF-2012-123-014,False
7,1,toc1_e7,P&IDREFRIGERATIONUNIT,P1-REF-2012-123-001,False
8,1,toc1_e8,GENERALARRANGEMENTDRAWING,P1-REF-2012-123-003,False
9,1,toc1_e9,FOUNDATIONLAYOUT,P1-REF-2012-123-012,False

Total retenues : 42 / 296

In [31]:
retenues = overview[overview["retenue"]].reset_index(drop=True)
print(f"\n=== Sections retenues (total {len(retenues)}) ===")
display(retenues.head(10))

=== Sections retenues (total 42) ===

,toc_region,section_id,title,page,retenue
0,1,toc1_e11,AIRCOOLERCONDENSERDATASHEET,P1-REF-DSS-12-123-011,True
1,1,toc1_e12,AIRCOOLERCONDENSERGENERALARRANGEMENT,P1-REF-2012-123-005,True
2,1,toc1_e17,ECONOMIZERDATASHEET,P1-REF-DSS-12-123-012,True
3,1,toc1_e19,KODRUMDATASHEET,P1-REF-DSS-12-123-013,True
4,1,toc1_e21,OILCOOLERDATASHEET,P1-REF-DSS-12-123-014,True
5,1,toc1_e23,RECEIVERDATASHEET,P1-REF-DSS-12-123-017,True
6,1,toc1_e25,OILSEPARATORDATASHEET,P1-REF-DSS-12-123-016,True
7,1,toc1_e27,SUCTIONFILTERDATASHEET,P1-REF-DSS-12-123-018,True
8,1,toc1_e29,OILFILTERDATASHEET,P1-REF-DSS-12-123-015,True
9,1,toc1_e39,COMPRESSORDATASHEETS,P1-REF-DSS-12-123-003,True

## 7. Pour aller plus loin

- `ocr_table_entries_for_page` réutilise `TOCDetector._parse_table` tel
  quel -- si le format des lignes OCR diffère trop du format natif
  (colonnes fusionnées, bruit), c'est ce parseur qu'il faut ajuster, pas
  cette cellule.
- `organize_region` dédoublonne sur le texte du titre en minuscules ; sur
  un vrai document, affinez si les titres OCR et natifs diffèrent
  légèrement (accents, casse, espaces).
- Le nombre d'appels LLM #1 ici est **un par région de TOC détectée**
  (pas un par page, pas un global) -- ajustez `region_entries_to_payload`
  si vous préférez un seul appel fusionnant toutes les régions.