# Information Extraction from PDF Sections

This notebook tests the information extraction pipeline.

The pipeline performs the following steps:

1. Load the useful sections from the CSV file.
2. Extract text and tables from each section.
3. Use PaddleOCR as a fallback when native PDF extraction is insufficient.
4. Send each section to the LLM using `extract_with_llm`.
5. Run the LLM extraction for all sections in parallel.
6. Inspect and evaluate the extracted information.

## 0. Imports

In [1]:
from pathlib import Path
import pandas as pd
import sys

In [2]:
PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / "src").exists() and (PROJECT_ROOT.parent / "src").exists():
    PROJECT_ROOT = PROJECT_ROOT.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

In [3]:
from src.information_extraction import (
    load_sections,
    extract_page_content,
    process_section,
    process_sections_parallel
)

from src.ocr.ocr_pipeline import ocr_pipeline

c:\Users\intel\industry\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\intel\.paddlex\official_models\PP-DocLayout_plus-L`.
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\intel\.paddlex\official_models\SLANet`.
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\intel\.paddlex\official_models\PP-OCRv6_medium_rec`.

In [31]:
OUTPUT_DIR = PROJECT_ROOT / "results"

PDF_PATH = PROJECT_ROOT / "data" / "raw" / "AUSTCOLD.pdf"
SECTIONS_CSV = PROJECT_ROOT / "data" / "processed" / "resolved_sections.csv"

print("PDF:", PDF_PATH)
print("CSV:", SECTIONS_CSV)

PDF: c:\Users\intel\Downloads\industrial-equipment-data-extraction\data\raw\AUSTCOLD.pdf
CSV: c:\Users\intel\Downloads\industrial-equipment-data-extraction\data\processed\resolved_sections.csv

## 1. Load sections

In [5]:
sections = load_sections(SECTIONS_CSV)

print(f"Number of sections: {len(sections)}")

Number of sections: 15

In [6]:
sections_df = pd.DataFrame(sections)
sections_df

                                                title  start_page  end_page
0                          3.02 Compressor Data Sheet         107       115
1                    3.03 Compressor motor data sheet         116       154
2                            3.04 Oil Pump Data Sheet         155       156
3                      3.05 Oil Pump Motor Data Sheet         157       159
4                          3.06 Oil Cooler Data Sheet         160       165
5                       3.07 Oil separator data sheet         166       169
6                            3.08 Receiver data sheet         170       170
7                              3.09 Purger data sheet         171       173
8                          3.10 Economiser Data Sheet         174       178
9                3.11 Air Cooled Condenser data sheet         179       182
10           3.12 Air Cooled Condenser Fan Data Sheet         183       189
11                3.13 Condenser Fan Motor Data Sheet         190       192
12  3.14 Air Cooled Condenser Vibration Switch Dat...         193       198
13          3.15 Final stage oil separator data sheet         199       202
14                  3.16 Control valve data sheet - A         203      2870

## 2. Extract page content

In [7]:
test_page = sections[0]["start_page"]

page_result = extract_page_content(
    pdf_path=PDF_PATH,
    page_number=test_page,
    ocr_pipeline=ocr_pipeline,
    min_text_length=50,
    dpi=300
)

In [8]:
page_result

{'page': 107,
 'text': "NUMÉRO DU DOCUMENT A5114-TDS-18\nRÉVISION\n01\n02\n03\n04\n05\nDATE\nBY\nMH\nRÉV/APPR\nCS\n  N° DE JOB\nN° ITEM\n  PAGE\n1\nDE\n9\nN° RÉQ.\n1\nAPPLICABLE À :\n    PROPOS°\n      ACHAT\nCONFORME À L'EXÉCUTION\n2\nPOUR\nUNITÉ\n3\nSITE\nN° DE SÉRIE\n4\nSERVICE\nN° REQUIS\n5\nFABRICANT\nMODÈLE\nPILOTE  (6.1)\n6\nREMARQUE :INFORMATIONS À COMPLETER PAR L'ACHETEUR\nPAR LE FABRICANT\n7\nCONDITIONS DE FONCTIONNEMENT\n8\nCAS D'EXPLOITATION N°\n9\nTOUTES LES DONNÉES SONT SUR UNE BASE UNITAIRE\n10\n11\nPOINT CERTIFIÉ (          )   \n12\nGAZ TRAITÉS (VOIR ÉGALEMENT PAGE 2\n13\nCapacité requise Nm3/h (1,013 bar & 0 °C) (SEC) (3.46 & 3.60)\n14\nDÉBIT MASSE, KG/HR-  (MOUILLÉ)(SEC)\n15\nCONDITIONS D'ENTRÉE :\nBRIDE ORIFICE D'ENTRÉE COM\nCONNEXION DU CLIENT\n16\nPRESSION - absolue (bar) \n17\nTEMPÉRATURE (°C)\n18\nHUMIDITÉ RELATIVE (%)\n19\nMASSE MOLÉCULAIRE (M)\n20\nCp/Cv (K1) OU (KAVG) (5.1.15.4)\n21\nCOMPRESSIBILITÉ (Z1) OU (ZAVG) (5.1.15.5)\n22\nDÉBIT VOLUME ORIFICE D'ENTRÉE (\n3/h)\n(3 19)\n29-Oct-12\nMH\nCS\n23-Sep-11\n4-Jun-12\nA5114\nPCAP-205J/206J/10 - 16084\nMH\nCS\nDR\nDR\n255-V-100A/B/C/D-C-01\n11-Nov-11\n1-Feb-13\n-20\n-20\nFICHE DE DONNÉES (API 619 4TH ED.)\nCOMPLEXE JORF LASFAR-MAROC\nCompresseur de réfrigération\n4\nSiemens\n2\n3\n1\nHOWDEN\nWRViH255/19350\n4\nAmmoniac\n1,00\n0,94\n1.363\nAmmoniac\nAmmoniac\n1447\n772\n1464\n1\n17.03\n1.363\n1\n1.363\n17.03\n17.03\n1.363\n1.363\n1\nCompresseurs Howden\nAmmoniac\nAmmoniac\n1,00\n-20\n1590\n1,00\n1,00\n-20\n1524\n-20\nMAROC PHOSPHORE\nSI  UNITÉS (KPA)\nCS\nCS\nCOMPRESSEUR DE TYPE ROTATIF À DÉPLACEMENT POSITIF\n1\n1\nUnité de refroidissement\n255-V-100A/B/C/D-C-01\n5 (Conception)\n17.03\n17.03\n22\nDÉBIT VOLUME ORIFICE D'ENTRÉE (m3/h)   (3.19)\n23\nCONDITIONS DE DÉCHARGE :\nBRIDE DÉCHARGE COMPRESSEUR\n     CONNEXION DU CLIENT\n24\nPRESSION - absolue (bar) \n25\nTEMPÉRATURE (°C)\n26\nCp/Cv (K2) OU (KAVG)\n27\nCOMPRESSIBILITÉ (Z2) OU (ZAVG)\n28\nPOINT DE ROSÉE (°C)\n29\n30\nkW requis (TOUTES PERTES INCL)\n31\nVITESSE (TR/MIN)\n32\nRAPPORT DE PRESSION (R)\n33\nRENDEMENT VOLUMÉTRIQUE (%)\n34\nSILENCIEUX D P (bar) (6.9.3)\n35\nRÉGLAGE PRESSION- absolue (bar) (5.1.5)\n36\nCOURBE DE PERFORMANCE N°\n37\n38\nCONTRÔLE DE PROCESSUS : (6.4.2.1)\n39\nMÉTHODE :\nROBINET À TIROIRDE 100% à 15%\n40\nCONTOURNEMEN DE 15% À 0%\nPOUR\n41\nCONTOURNER :\nMANUEL\nAUTO\n42\nVARIATION DE LA VITESSE DE VITESSE CONSTANTE - SANS OBJET\n43\nAUTRE\n44\nSIGNAL :\nSOURCE\n45\nTYPE\n46\nGAMME :\nPOUR CONTRÔLE PNEUMATIQUE\nTR/MN @\n(bar) &\nTR/MN @\n(bar) \n47\nAUTRE\n48\nSERVICE :\nOBJECTIF SPÉCIAL (3.58)\nOBJECTIF GÉNÉRAL (3.15)\n49\nCONTINU\n  INTERMITTENT\nVEILLE (3.62)\nVIS SECHE (3.9)\nVIS NOYÉE  \n50 REMARQUES :\nLES DÉBITS-MASSE CONSTITUENT LES CAPACITÉS DES COMPRESSEURS AUX CONDITIONS FOURNIES PAR INTECSA\n51\n52\n53\n1\n1\n1\nSANS OBJET\n83\n1\n1\n5.01\n5.33\n2980\n-32,18\n2.065\nSANS OBJET\n80\n83\n83\n83\n2980\n2980\n2980\n2980\n5.01\n5.01\n5.01\n5,01\n5,01\n-32,18\n-32\n2.065\n2.065\n2,349\n2.065\n438\n519\n438\n438\n432\n5,01\n5,01\n-32,18\n-32,18\n5,01",
 'tables': [                      NUMÉRO DU DOCUMENT A5114-TDS-18  \
  0                                 Compresseurs Howden
  1                                                 NaN
  2                                                 NaN
  3   COMPRESSEUR DE TYPE ROTATIF À DÉPLACEMENT POSI...
  4                                                 NaN
  5
  6   1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\...
  7                                                 NaN
  8                                                 NaN
  9                                                 NaN
  10                                                NaN
  11                                                NaN
  12                                                NaN
  13                                                NaN
  14                                                NaN
  15                                                NaN
  16                                                NaN
  17                                                NaN

                                                    NaN       NaN  \
  0                                                 NaN       NaN
  1                                                 NaN       NaN
  2                                                 NaN       NaN
  3                                                 NaN       NaN
  4                                                 NaN       NaN
  5                                                 NaN       NaN
  6   APPLICABLE À : PROPOS° ACHAT CONFORME À L'EXÉC...       NaN
  7                        CONDITIONS DE FONCTIONNEMENT       NaN
  8   CAS D'EXPLOITATION N°\nTOUTES LES DONNÉES SONT...         1
  9                                                 NaN       NaN
  10                                                NaN
  11                                                NaN
  12                                                NaN  Ammoniac
  13                                                NaN
  14                                                NaN      1524
  15                                                          NaN
  16                                                          NaN
  17                                                          NaN

                                                    NaN  NaN        NaN  \
  0                                            RÉVISION  NaN         01
  1                                                DATE  NaN  23-Sep-11
  2                                                  BY  NaN         DR
  3                                            RÉV/APPR  NaN         CS
  4   N° DE JOB A5114 N° ITEM 255-V-100A/B/C/D-C-01\...  NaN        NaN
  5                                                 NaN  NaN        NaN
  6                                                 NaN  NaN        NaN
  7                                                 NaN  NaN        NaN
  8                                                 NaN             NaN
  9                                                 NaN  NaN        NaN
  10                                                NaN             NaN
  11                                                NaN             NaN
  12                                                NaN             NaN
  13                                                NaN             NaN
  14                                                NaN             NaN
  15                                                NaN  NaN        NaN
  16                                                NaN  NaN        NaN
  17                                                NaN  NaN        NaN

                        NaN        NaN       NaN       NaN       NaN        NaN  \
  0                     NaN         02       NaN        03       NaN         04
  1                     NaN  11-Nov-11       NaN  4-Jun-12       NaN  29-Oct-12
  2                     NaN         DR       NaN        MH       NaN         MH
  3                     NaN         CS       NaN        CS       NaN         CS
  4                     NaN        NaN       NaN       NaN       NaN        NaN
  5                     NaN        NaN       NaN       NaN       NaN        NaN
  6                     NaN        NaN       NaN       NaN       NaN        NaN
  7                     NaN        NaN       NaN       NaN       NaN        NaN
  8   CAS D'EXPLOITATION N°        NaN       NaN       NaN       NaN        NaN
  9                       2        NaN         3       NaN         4        NaN
  10                               NaN                 NaN                  NaN
  11                               NaN                 NaN                  NaN
  12               Ammoniac        NaN  Ammoniac       NaN  Ammoniac        NaN
  13                               NaN                 NaN                  NaN
  14                   1447        NaN      1590       NaN       772        NaN
  15                    NaN        NaN       NaN       NaN       NaN        NaN
  16                    NaN        NaN       NaN       NaN       NaN        NaN
  17                    NaN        NaN       NaN       NaN       NaN        NaN

                 NaN       NaN
  0              NaN        05
  1              NaN  1-Feb-13
  2              NaN        MH
  3              NaN        CS
  4              NaN       NaN
  5              NaN       NaN
  6              NaN       NaN
  7              NaN       NaN
  8              NaN       NaN
  9   5 (Conception)       NaN
  10                       NaN
  11                       NaN
  12        Ammoniac       NaN
  13                       NaN
  14            1464       NaN
  15             NaN       NaN
  16             NaN       NaN
  17             NaN       NaN  ,
      1,00     1,00   1,00   1,00   0,94
  0    -20      -20    -20    -20    -20
  1
  2  17.03    17.03  17.03  17.03  17.03
  3  1.363    1.363  1.363  1.363  1.363
  4      1        1      1      1      1
  5                                     ,

  0
  1  ,
            5,01         5,01    5,01    5,01    5,01
  0          -32       -32,18  -32,18  -32,18  -32,18
  1        2.065        2,349   2.065   2.065   2.065
  2            1            1       1       1       1
  3
  4
  5          438          519     438     438     432
  6         2980         2980    2980    2980    2980
  7         5.01         5.01    5.01    5.01    5.33
  8           83           80      83      83      83
  9   SANS OBJET  NaN     NaN     NaN     NaN     NaN
  10  SANS OBJET  NaN     NaN     NaN     NaN     NaN
  11              NaN     NaN     NaN     NaN     NaN
  12                                                 ,

  0
  1  ,

  0
  1
  2
  3  ],
 'method': 'native',
 'text_method': 'native_text',
 'table_method': 'native_table'}

## 3. Process one complete section

In [9]:
test_section = sections[0]

print(test_section)

{'title': '3.02 Compressor Data Sheet', 'start_page': 107, 'end_page': 115}

In [10]:
test_result = process_section(
    pdf_path=PDF_PATH,
    section=test_section,
    ocr_pipeline=ocr_pipeline,
    #llm=llm,
    dpi=300,
    min_text_length=50
)

Processing section: 3.02 Compressor Data Sheet (pages 107-115)

In [11]:
test_result

{'method': 'llm',
 'called': True,
 'result': {'family': {'value': None, 'confidence': 0.0, 'page': None},
  'asset_name': {'value': 'Compresseur de type rotatif à déplacement positif',
   'confidence': 1.0,
   'page': 107},
  'reference': {'value': '255-V-100A/B/C/D-C-01',
   'confidence': 1.0,
   'page': 107},
  'power': {'value': '610 kW', 'confidence': 1.0, 'page': 111},
  'outlier': {'value': None, 'confidence': 0.0, 'page': None},
  'manufacturer': {'value': 'HOWDEN', 'confidence': 1.0, 'page': 107},
  'asset_diagram': {'value': None, 'confidence': 0.0, 'page': None}}}

## 4. Parallel LLM Extraction

Each useful section is processed independently.

The LLM extraction is executed in parallel using a `ThreadPoolExecutor`.

The number of simultaneous LLM requests is controlled by `max_workers`.

For example:

- `max_workers=1` → sequential execution
- `max_workers=2` → 2 simultaneous requests
- `max_workers=4` → 4 simultaneous requests

We start with 4 workers to avoid sending too many requests simultaneously.

In [12]:
results = process_sections_parallel(
    pdf_path=PDF_PATH,
    csv_path=SECTIONS_CSV,
    max_workers=4,
    dpi=300,
    min_text_length=50
)

Found 15 sections.

Starting parallel processing with 4 workers...

Processing section: 3.02 Compressor Data Sheet (pages 107-115)
Processing section: 3.03 Compressor motor data sheet (pages 116-154)
Processing section: 3.04 Oil Pump Data Sheet (pages 155-156)
Processing section: 3.05 Oil Pump Motor Data Sheet (pages 157-159)
Native extraction insufficient on page 157. Using OCR...
[1/5] Loaded: PDF 'AUSTCOLD.pdf' (Page 157, 300 DPI)
[2/5] Preprocessing completed
Processing section: 3.06 Oil Cooler Data Sheet (pages 160-165)✗ Failed: 3.05 Oil Pump Motor Data Sheet → (Unimplemented) ConvertPirAttribute2RuntimeAttribute not support [pir::ArrayAttribute<pir::DoubleAttribute>]  (at ..\paddle\fluid\framework\new_executor\instruction\onednn\onednn_instruction.cc:118)


Native extraction insufficient on page 116. Using OCR...
[1/5] Loaded: PDF 'AUSTCOLD.pdf' (Page 116, 300 DPI)
[2/5] Preprocessing completed
Processing section: 3.07 Oil separator data sheet (pages 166-169)
✗ Failed: 3.03 Compressor motor data sheet → (Unimplemented) ConvertPirAttribute2RuntimeAttribute not support [pir::ArrayAttribute<pir::DoubleAttribute>]  (at ..\paddle\fluid\framework\new_executor\instruction\onednn\onednn_instruction.cc:118)

Native extraction insufficient on page 160. Using OCR...
[1/5] Loaded: PDF 'AUSTCOLD.pdf' (Page 160, 300 DPI)
[2/5] Preprocessing completed
Processing section: 3.08 Receiver data sheet (pages 170-170)✗ Failed: 3.06 Oil Cooler Data Sheet → (Unimplemented) ConvertPirAttribute2RuntimeAttribute not support [pir::ArrayAttribute<pir::DoubleAttribute>]  (at ..\paddle\fluid\framework\new_executor\instruction\onednn\onednn_instruction.cc:118)


Processing section: 3.09 Purger data sheet (pages 171-173)
✓ Finished: 3.04 Oil Pump Data Sheet
Native extraction insufficient on page 167. Using OCR...
[1/5] Loaded: PDF 'AUSTCOLD.pdf' (Page 167, 300 DPI)
[2/5] Preprocessing completed
Processing section: 3.10 Economiser Data Sheet (pages 174-178)✗ Failed: 3.07 Oil separator data sheet → (Unimplemented) ConvertPirAttribute2RuntimeAttribute not support [pir::ArrayAttribute<pir::DoubleAttribute>]  (at ..\paddle\fluid\framework\new_executor\instruction\onednn\onednn_instruction.cc:118)


Processing section: 3.11 Air Cooled Condenser data sheet (pages 179-182)
✓ Finished: 3.08 Receiver data sheet
Native extraction insufficient on page 171. Using OCR...
[1/5] Loaded: PDF 'AUSTCOLD.pdf' (Page 171, 300 DPI)
[2/5] Preprocessing completed
Processing section: 3.12 Air Cooled Condenser Fan Data Sheet (pages 183-189)✗ Failed: 3.09 Purger data sheet → (Unimplemented) ConvertPirAttribute2RuntimeAttribute not support [pir::ArrayAttribute<pir::DoubleAttribute>]  (at ..\paddle\fluid\framework\new_executor\instruction\onednn\onednn_instruction.cc:118)


Native extraction insufficient on page 179. Using OCR...
[1/5] Loaded: PDF 'AUSTCOLD.pdf' (Page 179, 300 DPI)
[2/5] Preprocessing completed
Processing section: 3.13 Condenser Fan Motor Data Sheet (pages 190-192)✗ Failed: 3.11 Air Cooled Condenser data sheet → (Unimplemented) ConvertPirAttribute2RuntimeAttribute not support [pir::ArrayAttribute<pir::DoubleAttribute>]  (at ..\paddle\fluid\framework\new_executor\instruction\onednn\onednn_instruction.cc:118)


Native extraction insufficient on page 174. Using OCR...
[1/5] Loaded: PDF 'AUSTCOLD.pdf' (Page 174, 300 DPI)
[2/5] Preprocessing completed
Processing section: 3.14 Air Cooled Condenser Vibration Switch Data Sheet (pages 193-198)✗ Failed: 3.10 Economiser Data Sheet → (Unimplemented) ConvertPirAttribute2RuntimeAttribute not support [pir::ArrayAttribute<pir::DoubleAttribute>]  (at ..\paddle\fluid\framework\new_executor\instruction\onednn\onednn_instruction.cc:118)


Native extraction insufficient on page 183. Using OCR...
[1/5] Loaded: PDF 'AUSTCOLD.pdf' (Page 183, 300 DPI)
[2/5] Preprocessing completed
Processing section: 3.15 Final stage oil separator data sheet (pages 199-202)✗ Failed: 3.12 Air Cooled Condenser Fan Data Sheet → (Unimplemented) ConvertPirAttribute2RuntimeAttribute not support [pir::ArrayAttribute<pir::DoubleAttribute>]  (at ..\paddle\fluid\framework\new_executor\instruction\onednn\onednn_instruction.cc:118)


Native extraction insufficient on page 190. Using OCR...Native extraction insufficient on page 193. Using OCR...

[1/5] Loaded: PDF 'AUSTCOLD.pdf' (Page 193, 300 DPI)
[2/5] Preprocessing completed
[1/5] Loaded: PDF 'AUSTCOLD.pdf' (Page 190, 300 DPI)
[2/5] Preprocessing completed
Processing section: 3.16 Control valve data sheet - A (pages 203-2870)✗ Failed: 3.14 Air Cooled Condenser Vibration Switch Data Sheet → (Unimplemented) ConvertPirAttribute2RuntimeAttribute not support [pir::ArrayAttribute<pir::DoubleAttribute>]  (at ..\paddle\fluid\framework\new_executor\instruction\onednn\onednn_instruction.cc:118)

✗ Failed: 3.13 Condenser Fan Motor Data Sheet → (Unimplemented) ConvertPirAttribute2RuntimeAttribute not support [pir::ArrayAttribute<pir::DoubleAttribute>]  (at ..\paddle\fluid\framework\new_executor\instruction\onednn\onednn_instruction.cc:118)


Native extraction insufficient on page 199. Using OCR...
[1/5] Loaded: PDF 'AUSTCOLD.pdf' (Page 199, 300 DPI)
[2/5] Preprocessing completed
✗ Failed: 3.15 Final stage oil separator data sheet → (Unimplemented) ConvertPirAttribute2RuntimeAttribute not support [pir::ArrayAttribute<pir::DoubleAttribute>]  (at ..\paddle\fluid\framework\new_executor\instruction\onednn\onednn_instruction.cc:118)

Native extraction insufficient on page 203. Using OCR...
[1/5] Loaded: PDF 'AUSTCOLD.pdf' (Page 203, 300 DPI)
[2/5] Preprocessing completed
✗ Failed: 3.16 Control valve data sheet - A → (Unimplemented) ConvertPirAttribute2RuntimeAttribute not support [pir::ArrayAttribute<pir::DoubleAttribute>]  (at ..\paddle\fluid\framework\new_executor\instruction\onednn\onednn_instruction.cc:118)

✓ Finished: 3.02 Compressor Data Sheet

All sections have been processed.

In [13]:
print("Number of sections:", len(sections))
print("Number of results:", len(results))

Number of sections: 15
Number of results: 15

In [14]:
failed_results = [
    result
    for result in results
    if result.get("error") is not None
]

print(f"Failed sections: {len(failed_results)}")

Failed sections: 12

In [24]:
results_df = pd.DataFrame([
    {
        "title": result["title"],
        "start_page": result["start_page"],
        "end_page": result["end_page"],
        #"num_tables": len(result["tables"]),
        #"methods": ", ".join(set(result["extraction_methods"])),
        "success": result.get("error") is None,
        "error": result.get("error")
    }
    for result in results
])

results_df

,title,start_page,end_page,success,error
0,3.02 Compressor Data Sheet,107,115,True,NaN
1,3.03 Compressor motor data sheet,116,154,False,(Unimplemented) ConvertPirAttribute2RuntimeAtt...
2,3.04 Oil Pump Data Sheet,155,156,True,NaN
3,3.05 Oil Pump Motor Data Sheet,157,159,False,(Unimplemented) ConvertPirAttribute2RuntimeAtt...
4,3.06 Oil Cooler Data Sheet,160,165,False,(Unimplemented) ConvertPirAttribute2RuntimeAtt...
5,3.07 Oil separator data sheet,166,169,False,(Unimplemented) ConvertPirAttribute2RuntimeAtt...
6,3.08 Receiver data sheet,170,170,True,NaN
7,3.09 Purger data sheet,171,173,False,(Unimplemented) ConvertPirAttribute2RuntimeAtt...
8,3.10 Economiser Data Sheet,174,178,False,(Unimplemented) ConvertPirAttribute2RuntimeAtt...
9,3.11 Air Cooled Condenser data sheet,179,182,False,(Unimplemented) ConvertPirAttribute2RuntimeAtt...
10,3.12 Air Cooled Condenser Fan Data Sheet,183,189,False,(Unimplemented) ConvertPirAttribute2RuntimeAtt...
11,3.13 Condenser Fan Motor Data Sheet,190,192,False,(Unimplemented) ConvertPirAttribute2RuntimeAtt...
12,3.14 Air Cooled Condenser Vibration Switch Dat...,193,198,False,(Unimplemented) ConvertPirAttribute2RuntimeAtt...
13,3.15 Final stage oil separator data sheet,199,202,False,(Unimplemented) ConvertPirAttribute2RuntimeAtt...
14,3.16 Control valve data sheet - A,203,2870,False,(Unimplemented) ConvertPirAttribute2RuntimeAtt...

In [26]:
for result in results:
    print()
    print(f"SECTION: {result['title']}")
    print("-" * 100)

    print(result["llm_result"])

SECTION: 3.02 Compressor Data Sheet
----------------------------------------------------------------------------------------------------
{'method': 'llm', 'called': True, 'result': {'family': {'value': None, 'confidence': 0.0, 'page': None}, 'asset_name': {'value': 'Compresseur de réfrigération', 'confidence': 1.0, 'page': 107}, 'reference': {'value': '255-V-100A/B/C/D-C-01', 'confidence': 1.0, 'page': 107}, 'power': {'value': '610 kW', 'confidence': 1.0, 'page': 111}, 'outlier': {'value': None, 'confidence': 0.0, 'page': None}, 'manufacturer': {'value': 'Howden', 'confidence': 1.0, 'page': 107}, 'asset_diagram': {'value': None, 'confidence': 0.0, 'page': None}}}

SECTION: 3.03 Compressor motor data sheet
----------------------------------------------------------------------------------------------------
None

SECTION: 3.04 Oil Pump Data Sheet
----------------------------------------------------------------------------------------------------
{'method': 'llm', 'called': True, 'result': {'family': {'value': None, 'confidence': 0.0, 'page': None}, 'asset_name': {'value': 'POMPE À HUILE', 'confidence': 1.0, 'page': 156}, 'reference': {'value': 'LQE4076-CCCNR0S-M180', 'confidence': 1.0, 'page': 156}, 'power': {'value': '15 kW', 'confidence': 1.0, 'page': 155}, 'outlier': {'value': None, 'confidence': 0.0, 'page': None}, 'manufacturer': {'value': 'VIKING PUMP', 'confidence': 1.0, 'page': 156}, 'asset_diagram': {'value': 'FICHE DE DONNÉES - POMPE À HUILE', 'confidence': 1.0, 'page': 156}}}

SECTION: 3.05 Oil Pump Motor Data Sheet
----------------------------------------------------------------------------------------------------
None

SECTION: 3.06 Oil Cooler Data Sheet
----------------------------------------------------------------------------------------------------
None

SECTION: 3.07 Oil separator data sheet
----------------------------------------------------------------------------------------------------
None

SECTION: 3.08 Receiver data sheet
----------------------------------------------------------------------------------------------------
{'method': 'llm', 'called': True, 'result': {'family': {'value': None, 'confidence': 0.0, 'page': None}, 'asset_name': {'value': 'Récepteur de Liquide', 'confidence': 1.0, 'page': 170}, 'reference': {'value': 'A5114-0800', 'confidence': 1.0, 'page': 170}, 'power': {'value': None, 'confidence': 0.0, 'page': None}, 'outlier': {'value': None, 'confidence': 0.0, 'page': None}, 'manufacturer': {'value': 'Britannia', 'confidence': 1.0, 'page': 170}, 'asset_diagram': {'value': None, 'confidence': 0.0, 'page': None}}}

SECTION: 3.09 Purger data sheet
----------------------------------------------------------------------------------------------------
None

SECTION: 3.10 Economiser Data Sheet
----------------------------------------------------------------------------------------------------
None

SECTION: 3.11 Air Cooled Condenser data sheet
----------------------------------------------------------------------------------------------------
None

SECTION: 3.12 Air Cooled Condenser Fan Data Sheet
----------------------------------------------------------------------------------------------------
None

SECTION: 3.13 Condenser Fan Motor Data Sheet
----------------------------------------------------------------------------------------------------
None

SECTION: 3.14 Air Cooled Condenser Vibration Switch Data Sheet
----------------------------------------------------------------------------------------------------
None

SECTION: 3.15 Final stage oil separator data sheet
----------------------------------------------------------------------------------------------------
None

SECTION: 3.16 Control valve data sheet - A
----------------------------------------------------------------------------------------------------
None

In [29]:
print(results[0]["llm_result"])

{'method': 'llm', 'called': True, 'result': {'family': {'value': None, 'confidence': 0.0, 'page': None}, 'asset_name': {'value': 'Compresseur de réfrigération', 'confidence': 1.0, 'page': 107}, 'reference': {'value': '255-V-100A/B/C/D-C-01', 'confidence': 1.0, 'page': 107}, 'power': {'value': '610 kW', 'confidence': 1.0, 'page': 111}, 'outlier': {'value': None, 'confidence': 0.0, 'page': None}, 'manufacturer': {'value': 'Howden', 'confidence': 1.0, 'page': 107}, 'asset_diagram': {'value': None, 'confidence': 0.0, 'page': None}}}

In [33]:
results_df.to_json(OUTPUT_DIR / "extracted_sections.json", orient="records", indent=2)